export type ProjectStatus = "draft" | "active" | "on_hold" | "completed" | "cancelled";
export type TimeStatus = "draft" | "submitted" | "approved" | "rejected" | "cancelled";
export type RecognitionStatus = "draft" | "pending_approval" | "posted" | "reversed" | "cancelled";

export type BusinessProject = {
  id: string;
  project_code: string;
  name: string;
  customer_id: string | null;
  customer_name: string | null;
  branch_id: string | null;
  branch_name: string | null;
  manager_user_id: string | null;
  manager_name: string | null;
  billing_model: "fixed_price" | "time_and_materials" | "internal";
  recognition_method: "none" | "cost_to_cost";
  status: ProjectStatus;
  starts_on: string;
  ends_on: string | null;
  contract_currency: string;
  contract_value_transaction: number;
  contract_exchange_rate: number;
  contract_value_base: number;
  estimated_total_cost_base: number;
  budget_cost_base: number;
  budget_revenue_base: number;
  budget_hours: number;
  approved_hours: number;
  labor_cost_base: number;
  billable_time_base: number;
  external_cost_base: number;
  actual_cost_base: number;
  billed_revenue_base: number;
  recognized_revenue_base: number;
  gross_profit_base: number;
  completion_percent: number;
  wip_asset_base: number;
  deferred_revenue_base: number;
  submitted_time_count: number;
  open_milestone_count: number;
  notes: string | null;
};

export type ProjectCostCode = { id: string; code: string; name: string; category: string; active: boolean };
export type ProjectBudget = { id: string; project_id: string; cost_code_id: string; cost_code: string; cost_code_name: string; budget_cost_base: number; budget_revenue_base: number; budget_hours: number; notes: string | null };
export type ProjectMilestone = { id: string; project_id: string; project_code: string; project_name: string; title: string; due_on: string | null; status: string; completion_percent: number; notes: string | null };
export type ProjectTimeEntry = { id: string; project_id: string; project_code: string; project_name: string; cost_code_id: string; cost_code: string; cost_code_name: string; employee_id: string | null; employee_name: string | null; work_date: string; hours: number; cost_rate_base: number; billing_rate_base: number; approved_cost_base: number; approved_billable_base: number; description: string; status: TimeStatus; rejection_reason: string | null; created_by: string | null; submitted_by: string | null };
export type ProjectAllocation = { id: string; project_id: string; project_code: string; project_name: string; cost_code_id: string; cost_code: string; cost_code_name: string; source_type: "sales_invoice_line" | "supplier_bill_line"; source_document_code: string; source_date: string; direction: "revenue" | "cost"; source_amount_base: number; allocated_amount_base: number; effective_amount_base: number; description: string | null };
export type ProjectRecognitionRun = { id: string; project_id: string; project_code: string; project_name: string; recognition_date: string; status: RecognitionStatus; actual_cost_to_date: number; estimated_total_cost_base: number; completion_percent: number; contract_value_base: number; billed_revenue_to_date: number; target_revenue_to_date: number; current_adjustment_base: number; desired_wip_asset_base: number; desired_deferred_revenue_base: number; approval_request_id: string | null; approval_status: string | null; approval_code: string | null; journal_entry_id: string | null; reversal_journal_entry_id: string | null; notes: string | null };
export type ProjectSourceCandidate = { source_type: "sales_invoice_line" | "supplier_bill_line"; source_line_id: string; source_document_id: string; source_document_code: string; source_date: string; description: string; direction: "revenue" | "cost"; source_amount_base: number; current_net_base: number; allocated_base: number; available_base: number; party_name: string | null };
export type ProjectAudit = { id: number; project_id: string | null; project_code: string | null; action: string; details: Record<string, unknown>; created_at: string };
export type ProjectBranch = { id: string; code: string; name: string; is_primary: boolean };
export type ProjectCustomer = { id: string; name: string; currency: string };
export type ProjectEmployee = { id: string; employee_code: string; name: string; branch_id: string | null; job_title: string | null };
export type ProjectMember = { user_id: string; name: string; role: string; branch_access_mode: string };

export type BusinessProjectsSnapshot = {
  business_id: string;
  base_currency: string;
  capabilities: { company_wide: boolean; can_manage: boolean; can_time: boolean; can_recognize: boolean };
  settings: { default_cost_rate_base?: number; default_billing_rate_base?: number };
  summary: { project_count: number; active_projects: number; on_hold_projects: number; contract_value_base: number; budget_cost_base: number; actual_cost_base: number; billed_revenue_base: number; recognized_revenue_base: number; gross_profit_base: number; wip_asset_base: number; deferred_revenue_base: number; submitted_time_count: number };
  projects: BusinessProject[];
  cost_codes: ProjectCostCode[];
  budgets: ProjectBudget[];
  milestones: ProjectMilestone[];
  time_entries: ProjectTimeEntry[];
  allocations: ProjectAllocation[];
  recognition_runs: ProjectRecognitionRun[];
  source_candidates: ProjectSourceCandidate[];
  branches: ProjectBranch[];
  customers: ProjectCustomer[];
  employees: ProjectEmployee[];
  members: ProjectMember[];
  audit_log: ProjectAudit[];
};
