import type { DeterministicFinanceAnswer } from "@/lib/ai/deterministic-finance-chat";
import type { AppLanguage } from "@/lib/i18n/config";

type Replacement = readonly [string, string];

const REPLACEMENTS: Record<Exclude<AppLanguage, "en">, readonly Replacement[]> = {
  ur: [
    ["You earned ", "آپ نے "],
    ["You spent ", "آپ نے "],
    ["Your net spending", "آپ کا خالص خرچ"],
    ["Your current payable amount is ", "آپ کی موجودہ واجب الادا رقم "],
    ["You currently have no outstanding payable amount recorded.", "آپ کے ریکارڈ میں اس وقت کوئی بقایا واجب الادا رقم نہیں ہے۔"],
    ["You do not have any recorded investment assets yet.", "آپ کے پاس ابھی کوئی ریکارڈ شدہ سرمایہ کاری اثاثہ نہیں ہے۔"],
    ["You do not have any recorded investment positions yet.", "آپ کے پاس ابھی کوئی ریکارڈ شدہ سرمایہ کاری پوزیشن نہیں ہے۔"],
    ["You have ", "آپ کے پاس "],
    [" accounts in total: ", " اکاؤنٹس ہیں: "],
    [" active and ", " فعال اور "],
    [" inactive or archived.", " غیر فعال یا محفوظ شدہ ہیں۔"],
    [" active account", " فعال اکاؤنٹ"],
    [" distinct recorded asset", " منفرد ریکارڈ شدہ اثاثہ"],
    ["These are stored across ", "یہ "],
    [" investment purchase records.", " سرمایہ کاری خرید ریکارڈز میں محفوظ ہیں۔"],
    ["during ", "کے دوران "],
    ["across ", "کل "],
    [" recorded income transaction", " ریکارڈ شدہ آمدنی ٹرانزیکشن"],
    [" recorded expense transaction", " ریکارڈ شدہ خرچ ٹرانزیکشن"],
    [" expense transaction", " خرچ ٹرانزیکشن"],
    [" outstanding record", " بقایا ریکارڈ"],
    [" in expenses minus ", " خرچ منفی "],
    [" in refunds", " ریفنڈز"],
    [" in refunds, ", " ریفنڈز، "],
    [" on ", " پر "],
    [" was ", " تھا "],
    [" is overdue.", " زائد المیعاد ہے۔"],
    [" are overdue.", " زائد المیعاد ہیں۔"],
    ["I could not match an exact recorded expense category in your question.", "میں آپ کے سوال میں کسی درست ریکارڈ شدہ خرچ کی کیٹیگری سے مطابقت نہیں کر سکا۔"],
    ["Available categories include: ", "دستیاب کیٹیگریز: "],
    ["I could not match an exact recorded expense category, so I did not return the total spending as a substitute.", "درست خرچ کی کیٹیگری نہیں ملی، اس لیے میں نے اندازاً کل خرچ نہیں دکھایا۔"],
    ["I could not match an exact recorded asset name in your question.", "میں آپ کے سوال میں کسی درست ریکارڈ شدہ اثاثے کے نام سے مطابقت نہیں کر سکا۔"],
    ["Your recorded assets are: ", "آپ کے ریکارڈ شدہ اثاثے: "],
    ["No recorded ", "کوئی ریکارڈ شدہ "],
    [" investment positions were purchased during ", " سرمایہ کاری پوزیشنز اس مدت میں نہیں خریدی گئیں: "],
    ["An exact profit calculation for ", "درست منافع کا حساب "],
    [" is not available because one or more matched positions are missing a valid quantity, purchase price, or current price.", " کے لیے دستیاب نہیں کیونکہ ایک یا زیادہ پوزیشنز میں درست مقدار، خرید قیمت یا موجودہ قیمت موجود نہیں۔"],
    ["Based on recorded current prices, ", "ریکارڈ شدہ موجودہ قیمتوں کے مطابق، "],
    [" has an unrealized profit of ", " کا غیر حقیقی منافع "],
    [" has an unrealized loss of ", " کا غیر حقیقی نقصان "],
    ["Recorded cost is ", "ریکارڈ شدہ لاگت "],
    [" and current value is ", " اور موجودہ قدر "],
    ["This is a current unrealized result for positions bought in that period, not historical or realized profit for the period.", "یہ اس مدت میں خریدی گئی پوزیشنز کا موجودہ غیر حقیقی نتیجہ ہے، تاریخی یا وصول شدہ منافع نہیں۔"],
    ["quantity unavailable", "مقدار دستیاب نہیں"],
    ["invested amount unavailable", "سرمایہ کاری کی رقم دستیاب نہیں"],
    ["current value unavailable because a current price is missing", "موجودہ قیمت نہ ہونے کی وجہ سے موجودہ قدر دستیاب نہیں"],
    ["quantity ", "مقدار "],
    [" units", " یونٹس"],
    ["invested ", "سرمایہ کاری "],
    ["current value ", "موجودہ قدر "],
    ["unrealized profit ", "غیر حقیقی منافع "],
    ["unrealized loss ", "غیر حقیقی نقصان "],
    ["Portfolio total: ", "پورٹ فولیو کل: "],
    ["Some records are incomplete, so I did not provide a potentially misleading portfolio total.", "کچھ ریکارڈ نامکمل ہیں، اس لیے میں نے ممکنہ طور پر گمراہ کن پورٹ فولیو کل نہیں دیا۔"],
    ["How much did I spend in the same period?", "اسی مدت میں میں نے کتنا خرچ کیا؟"],
    ["How much did I earn in the same period?", "اسی مدت میں میں نے کتنی آمدنی حاصل کی؟"],
    ["How many assets do I have?", "میرے پاس کتنے اثاثے ہیں؟"],
    ["How many accounts do I have?", "میرے پاس کتنے اکاؤنٹس ہیں؟"],
    ["How much is currently payable?", "اس وقت کتنی رقم واجب الادا ہے؟"],
    ["How many payable records are overdue?", "کتنے واجب الادا ریکارڈز زائد المیعاد ہیں؟"],
    ["How much profit do I have on ", "مجھے اس پر کتنا منافع ہے: "],
    ["How much did I spend on ", "میں نے اس پر کتنا خرچ کیا: "],
    [" all time?", " تمام مدت میں؟"],
  ],
  ar: [
    ["You earned ", "لقد كسبت "],
    ["You spent ", "لقد أنفقت "],
    ["Your net spending", "صافي إنفاقك"],
    ["Your current payable amount is ", "المبلغ المستحق حاليًا هو "],
    ["You currently have no outstanding payable amount recorded.", "لا يوجد لديك حاليًا مبلغ مستحق مسجل."],
    ["You do not have any recorded investment assets yet.", "ليس لديك أي أصول استثمارية مسجلة حتى الآن."],
    ["You do not have any recorded investment positions yet.", "ليس لديك أي مراكز استثمارية مسجلة حتى الآن."],
    ["You have ", "لديك "],
    [" accounts in total: ", " حسابات إجمالًا: "],
    [" active and ", " نشطة و"],
    [" inactive or archived.", " غير نشطة أو مؤرشفة."],
    [" active account", " حساب نشط"],
    [" distinct recorded asset", " أصل مسجل مميز"],
    ["during ", "خلال "],
    ["across ", "عبر "],
    [" recorded income transaction", " معاملة دخل مسجلة"],
    [" recorded expense transaction", " معاملة مصروف مسجلة"],
    [" expense transaction", " معاملة مصروف"],
    [" outstanding record", " سجل مستحق"],
    [" in expenses minus ", " مصروفات ناقص "],
    [" in refunds", " مبالغ مستردة"],
    [" on ", " على "],
    [" was ", " كان "],
    [" is overdue.", " متأخر الاستحقاق."],
    [" are overdue.", " متأخرة الاستحقاق."],
    ["I could not match an exact recorded expense category in your question.", "لم أتمكن من مطابقة فئة مصروف مسجلة بدقة في سؤالك."],
    ["Available categories include: ", "الفئات المتاحة تشمل: "],
    ["I could not match an exact recorded expense category, so I did not return the total spending as a substitute.", "لم أجد فئة مصروف مطابقة، لذلك لم أقدّم إجماليًا تقديريًا بديلًا."],
    ["I could not match an exact recorded asset name in your question.", "لم أتمكن من مطابقة اسم أصل مسجل بدقة في سؤالك."],
    ["Your recorded assets are: ", "أصولك المسجلة هي: "],
    ["Based on recorded current prices, ", "بناءً على الأسعار الحالية المسجلة، "],
    [" has an unrealized profit of ", " لديه ربح غير محقق قدره "],
    [" has an unrealized loss of ", " لديه خسارة غير محققة قدرها "],
    ["Recorded cost is ", "التكلفة المسجلة هي "],
    [" and current value is ", " والقيمة الحالية هي "],
    ["quantity unavailable", "الكمية غير متاحة"],
    ["invested amount unavailable", "المبلغ المستثمر غير متاح"],
    ["current value unavailable because a current price is missing", "القيمة الحالية غير متاحة لعدم وجود سعر حالي"],
    ["quantity ", "الكمية "],
    [" units", " وحدات"],
    ["invested ", "المستثمر "],
    ["current value ", "القيمة الحالية "],
    ["unrealized profit ", "ربح غير محقق "],
    ["unrealized loss ", "خسارة غير محققة "],
    ["Portfolio total: ", "إجمالي المحفظة: "],
    ["Some records are incomplete, so I did not provide a potentially misleading portfolio total.", "بعض السجلات غير مكتملة، لذلك لم أقدّم إجمالي محفظة قد يكون مضللًا."],
    ["How much did I spend in the same period?", "كم أنفقت في الفترة نفسها؟"],
    ["How much did I earn in the same period?", "كم كسبت في الفترة نفسها؟"],
    ["How many assets do I have?", "كم عدد الأصول التي أملكها؟"],
    ["How many accounts do I have?", "كم عدد حساباتي؟"],
    ["How much is currently payable?", "كم المبلغ المستحق حاليًا؟"],
    ["How many payable records are overdue?", "كم سجلًا مستحقًا متأخرًا؟"],
    ["How much profit do I have on ", "كم ربحي في "],
  ],
  hi: [
    ["You earned ", "आपने "],
    ["You spent ", "आपने "],
    ["Your net spending", "आपका शुद्ध खर्च"],
    ["Your current payable amount is ", "आपकी वर्तमान देय राशि "],
    ["You currently have no outstanding payable amount recorded.", "अभी कोई बकाया देय राशि दर्ज नहीं है।"],
    ["You do not have any recorded investment assets yet.", "अभी कोई निवेश संपत्ति दर्ज नहीं है।"],
    ["You do not have any recorded investment positions yet.", "अभी कोई निवेश पोज़िशन दर्ज नहीं है।"],
    ["You have ", "आपके पास "],
    [" accounts in total: ", " कुल खाते हैं: "],
    [" active and ", " सक्रिय और "],
    [" inactive or archived.", " निष्क्रिय या संग्रहीत हैं।"],
    [" active account", " सक्रिय खाता"],
    [" distinct recorded asset", " अलग दर्ज संपत्ति"],
    ["during ", "के दौरान "],
    ["across ", "कुल "],
    [" recorded income transaction", " दर्ज आय लेन-देन"],
    [" recorded expense transaction", " दर्ज खर्च लेन-देन"],
    [" expense transaction", " खर्च लेन-देन"],
    [" outstanding record", " बकाया रिकॉर्ड"],
    [" in expenses minus ", " खर्च में से "],
    [" in refunds", " रिफंड घटाकर"],
    [" on ", " पर "],
    [" was ", " था "],
    [" is overdue.", " अतिदेय है।"],
    [" are overdue.", " अतिदेय हैं।"],
    ["I could not match an exact recorded expense category in your question.", "आपके प्रश्न में कोई सटीक दर्ज खर्च श्रेणी नहीं मिली।"],
    ["Available categories include: ", "उपलब्ध श्रेणियाँ: "],
    ["I could not match an exact recorded asset name in your question.", "आपके प्रश्न में कोई सटीक दर्ज संपत्ति नाम नहीं मिला।"],
    ["Your recorded assets are: ", "आपकी दर्ज संपत्तियाँ: "],
    ["Based on recorded current prices, ", "दर्ज मौजूदा कीमतों के आधार पर, "],
    [" has an unrealized profit of ", " का अप्राप्त लाभ "],
    [" has an unrealized loss of ", " की अप्राप्त हानि "],
    ["Recorded cost is ", "दर्ज लागत "],
    [" and current value is ", " और वर्तमान मूल्य "],
    ["quantity unavailable", "मात्रा उपलब्ध नहीं"],
    ["invested amount unavailable", "निवेश राशि उपलब्ध नहीं"],
    ["current value unavailable because a current price is missing", "मौजूदा कीमत न होने के कारण वर्तमान मूल्य उपलब्ध नहीं"],
    ["quantity ", "मात्रा "],
    [" units", " यूनिट"],
    ["invested ", "निवेशित "],
    ["current value ", "वर्तमान मूल्य "],
    ["unrealized profit ", "अप्राप्त लाभ "],
    ["unrealized loss ", "अप्राप्त हानि "],
    ["Portfolio total: ", "पोर्टफोलियो कुल: "],
    ["Some records are incomplete, so I did not provide a potentially misleading portfolio total.", "कुछ रिकॉर्ड अधूरे हैं, इसलिए संभावित रूप से भ्रामक पोर्टफोलियो कुल नहीं दिया गया।"],
    ["How much did I spend in the same period?", "इसी अवधि में मैंने कितना खर्च किया?"],
    ["How much did I earn in the same period?", "इसी अवधि में मैंने कितनी आय कमाई?"],
    ["How many assets do I have?", "मेरे पास कितनी संपत्तियाँ हैं?"],
    ["How many accounts do I have?", "मेरे पास कितने खाते हैं?"],
    ["How much is currently payable?", "अभी कितनी राशि देय है?"],
    ["How many payable records are overdue?", "कितने देय रिकॉर्ड अतिदेय हैं?"],
    ["How much profit do I have on ", "मुझे इस पर कितना लाभ है: "],
  ],
  es: [
    ["You earned ", "Ganaste "],
    ["You spent ", "Gastaste "],
    ["Your net spending", "Tu gasto neto"],
    ["Your current payable amount is ", "Tu importe pendiente actual es "],
    ["You currently have no outstanding payable amount recorded.", "Actualmente no tienes ningún importe pendiente registrado."],
    ["You do not have any recorded investment assets yet.", "Aún no tienes activos de inversión registrados."],
    ["You do not have any recorded investment positions yet.", "Aún no tienes posiciones de inversión registradas."],
    ["You have ", "Tienes "],
    [" accounts in total: ", " cuentas en total: "],
    [" active and ", " activas y "],
    [" inactive or archived.", " inactivas o archivadas."],
    [" active account", " cuenta activa"],
    [" distinct recorded asset", " activo registrado distinto"],
    ["during ", "durante "],
    ["across ", "en "],
    [" recorded income transaction", " transacción de ingreso registrada"],
    [" recorded expense transaction", " transacción de gasto registrada"],
    [" expense transaction", " transacción de gasto"],
    [" outstanding record", " registro pendiente"],
    [" in expenses minus ", " en gastos menos "],
    [" in refunds", " en reembolsos"],
    [" on ", " en "],
    [" was ", " fue "],
    [" is overdue.", " está vencido."],
    [" are overdue.", " están vencidos."],
    ["I could not match an exact recorded expense category in your question.", "No pude encontrar una categoría de gasto registrada exacta en tu pregunta."],
    ["Available categories include: ", "Las categorías disponibles incluyen: "],
    ["I could not match an exact recorded expense category, so I did not return the total spending as a substitute.", "No encontré una categoría de gasto exacta, así que no devolví un gasto total estimado como sustituto."],
    ["I could not match an exact recorded asset name in your question.", "No pude encontrar un nombre de activo registrado exacto en tu pregunta."],
    ["Your recorded assets are: ", "Tus activos registrados son: "],
    ["Based on recorded current prices, ", "Según los precios actuales registrados, "],
    [" has an unrealized profit of ", " tiene una ganancia no realizada de "],
    [" has an unrealized loss of ", " tiene una pérdida no realizada de "],
    ["Recorded cost is ", "El coste registrado es "],
    [" and current value is ", " y el valor actual es "],
    ["quantity unavailable", "cantidad no disponible"],
    ["invested amount unavailable", "importe invertido no disponible"],
    ["current value unavailable because a current price is missing", "valor actual no disponible porque falta un precio actual"],
    ["quantity ", "cantidad "],
    [" units", " unidades"],
    ["invested ", "invertido "],
    ["current value ", "valor actual "],
    ["unrealized profit ", "ganancia no realizada "],
    ["unrealized loss ", "pérdida no realizada "],
    ["Portfolio total: ", "Total de la cartera: "],
    ["Some records are incomplete, so I did not provide a potentially misleading portfolio total.", "Algunos registros están incompletos, así que no proporcioné un total de cartera potencialmente engañoso."],
    ["How much did I spend in the same period?", "¿Cuánto gasté en el mismo período?"],
    ["How much did I earn in the same period?", "¿Cuánto gané en el mismo período?"],
    ["How many assets do I have?", "¿Cuántos activos tengo?"],
    ["How many accounts do I have?", "¿Cuántas cuentas tengo?"],
    ["How much is currently payable?", "¿Cuánto está pendiente actualmente?"],
    ["How many payable records are overdue?", "¿Cuántos registros pendientes están vencidos?"],
    ["How much profit do I have on ", "¿Cuánta ganancia tengo en "],
  ],
};

const ADDRESS_PREFIX: Record<AppLanguage, (name: string) => string> = {
  en: (name) => `${name}, `,
  ur: (name) => `${name}، `,
  ar: (name) => `${name}، `,
  hi: (name) => `${name}, `,
  es: (name) => `${name}, `,
};

function replaceAllLiteral(value: string, search: string, replacement: string) {
  return value.split(search).join(replacement);
}

export function localizeVerifiedFinanceText(
  value: string,
  language: AppLanguage,
) {
  if (language === "en") return value;

  return REPLACEMENTS[language].reduce(
    (translated, [search, replacement]) =>
      replaceAllLiteral(translated, search, replacement),
    value,
  );
}

export function localizeVerifiedFinanceAnswer({
  result,
  language,
  displayName,
}: {
  result: DeterministicFinanceAnswer;
  language: AppLanguage;
  displayName: string;
}): DeterministicFinanceAnswer {
  const safeName = displayName.trim() || "there";
  const localizedAnswer = localizeVerifiedFinanceText(result.answer, language);

  return {
    answer: `${ADDRESS_PREFIX[language](safeName)}${localizedAnswer}`,
    followUps: result.followUps.map((followUp) =>
      localizeVerifiedFinanceText(followUp, language),
    ),
  };
}
