const React = require("react");
const Icons = require("./components");

const EXACT = Object.freeze({
  Activity: Icons.JalvoroAnalyticsIcon,
  AlertCircle: Icons.JalvoroErrorIcon,
  AlertTriangle: Icons.JalvoroWarningIcon,
  ArrowDown: Icons.JalvoroTrendDownIcon,
  ArrowDownLeft: Icons.JalvoroTrendDownIcon,
  ArrowDownRight: Icons.JalvoroTrendDownIcon,
  ArrowLeft: Icons.JalvoroArrowLeftIcon,
  ArrowRight: Icons.JalvoroArrowRightIcon,
  ArrowUp: Icons.JalvoroTrendUpIcon,
  ArrowUpLeft: Icons.JalvoroTrendUpIcon,
  ArrowUpRight: Icons.JalvoroTrendUpIcon,
  BadgeDollarSign: Icons.JalvoroIncomeIcon,
  Banknote: Icons.JalvoroCashIcon,
  BarChart: Icons.JalvoroAnalyticsIcon,
  BarChart2: Icons.JalvoroAnalyticsIcon,
  BarChart3: Icons.JalvoroAnalyticsIcon,
  Bell: Icons.JalvoroBellIcon,
  BellRing: Icons.JalvoroBellIcon,
  BookOpen: Icons.JalvoroFileIcon,
  Brain: Icons.JalvoroAiInsightsIcon,
  BrainCircuit: Icons.JalvoroAiInsightsIcon,
  Briefcase: Icons.JalvoroInvestmentsIcon,
  BriefcaseBusiness: Icons.JalvoroInvestmentsIcon,
  Building: Icons.JalvoroBankIcon,
  Building2: Icons.JalvoroBankIcon,
  Calendar: Icons.JalvoroCalendarIcon,
  CalendarClock: Icons.JalvoroCalendarIcon,
  CalendarDays: Icons.JalvoroCalendarIcon,
  Camera: Icons.JalvoroCameraIcon,
  ChartArea: Icons.JalvoroAnalyticsIcon,
  ChartBar: Icons.JalvoroAnalyticsIcon,
  ChartColumn: Icons.JalvoroAnalyticsIcon,
  ChartLine: Icons.JalvoroTrendUpIcon,
  Check: Icons.JalvoroCheckIcon,
  CheckCircle: Icons.JalvoroSuccessIcon,
  CheckCircle2: Icons.JalvoroSuccessIcon,
  ChevronDown: Icons.JalvoroChevronDownIcon,
  ChevronLeft: Icons.JalvoroArrowLeftIcon,
  ChevronRight: Icons.JalvoroChevronRightIcon,
  ChevronUp: Icons.JalvoroChevronDownIcon,
  CircleCheck: Icons.JalvoroSuccessIcon,
  CircleDollarSign: Icons.JalvoroCoinIcon,
  CircleHelp: Icons.JalvoroInfoIcon,
  CircleUser: Icons.JalvoroUserIcon,
  Clipboard: Icons.JalvoroFileIcon,
  ClipboardCheck: Icons.JalvoroSuccessIcon,
  Clock: Icons.JalvoroClockIcon,
  Clock3: Icons.JalvoroClockIcon,
  Cloud: Icons.JalvoroUploadIcon,
  CloudDownload: Icons.JalvoroDownloadIcon,
  CloudUpload: Icons.JalvoroUploadIcon,
  Coins: Icons.JalvoroCoinIcon,
  Copy: Icons.JalvoroCopyIcon,
  CreditCard: Icons.JalvoroCardIcon,
  Database: Icons.JalvoroAccountsIcon,
  DollarSign: Icons.JalvoroCoinIcon,
  Download: Icons.JalvoroDownloadIcon,
  Edit: Icons.JalvoroEditIcon,
  Edit2: Icons.JalvoroEditIcon,
  Ellipsis: Icons.JalvoroMoreIcon,
  EllipsisVertical: Icons.JalvoroMoreIcon,
  Eye: Icons.JalvoroEyeIcon,
  EyeOff: Icons.JalvoroEyeOffIcon,
  File: Icons.JalvoroFileIcon,
  FileBarChart: Icons.JalvoroReportsIcon,
  FileChartColumn: Icons.JalvoroReportsIcon,
  FileText: Icons.JalvoroFileIcon,
  Filter: Icons.JalvoroFilterIcon,
  Folder: Icons.JalvoroFolderIcon,
  FolderKanban: Icons.JalvoroFolderIcon,
  Gauge: Icons.JalvoroDashboardIcon,
  Gift: Icons.JalvoroSavingsIcon,
  Globe: Icons.JalvoroGlobeIcon,
  Goal: Icons.JalvoroGoalsIcon,
  HandCoins: Icons.JalvoroPayablesIcon,
  HelpCircle: Icons.JalvoroInfoIcon,
  Home: Icons.JalvoroDashboardIcon,
  Image: Icons.JalvoroImageIcon,
  Import: Icons.JalvoroImportIcon,
  Info: Icons.JalvoroInfoIcon,
  Key: Icons.JalvoroKeyIcon,
  Landmark: Icons.JalvoroBankIcon,
  LayoutDashboard: Icons.JalvoroDashboardIcon,
  Link: Icons.JalvoroLinkIcon,
  List: Icons.JalvoroListIcon,
  Loader: Icons.JalvoroPendingIcon,
  Loader2: Icons.JalvoroPendingIcon,
  Lock: Icons.JalvoroLockIcon,
  LogOut: Icons.JalvoroArrowRightIcon,
  Mail: Icons.JalvoroMailIcon,
  Menu: Icons.JalvoroMenuIcon,
  MessageCircle: Icons.JalvoroChatIcon,
  MessageSquare: Icons.JalvoroChatIcon,
  Minus: Icons.JalvoroCloseIcon,
  Moon: Icons.JalvoroPendingIcon,
  MoreHorizontal: Icons.JalvoroMoreIcon,
  MoreVertical: Icons.JalvoroMoreIcon,
  Package: Icons.JalvoroFolderIcon,
  PanelLeft: Icons.JalvoroSidebarIcon,
  Paperclip: Icons.JalvoroLinkIcon,
  Pencil: Icons.JalvoroPencilIcon,
  Percent: Icons.JalvoroTaxIcon,
  Phone: Icons.JalvoroPhoneIcon,
  PieChart: Icons.JalvoroBudgetIcon,
  Plus: Icons.JalvoroAddIcon,
  PlusCircle: Icons.JalvoroAddIcon,
  Printer: Icons.JalvoroReportsIcon,
  Receipt: Icons.JalvoroReceiptIcon,
  ReceiptText: Icons.JalvoroTransactionsIcon,
  Redo: Icons.JalvoroRedoIcon,
  RefreshCcw: Icons.JalvoroRefreshIcon,
  RefreshCw: Icons.JalvoroRefreshIcon,
  RotateCcw: Icons.JalvoroUndoIcon,
  Save: Icons.JalvoroDownloadIcon,
  Search: Icons.JalvoroSearchIcon,
  Send: Icons.JalvoroSendIcon,
  Settings: Icons.JalvoroSettingsIcon,
  Settings2: Icons.JalvoroSettingsIcon,
  Share: Icons.JalvoroShareIcon,
  Share2: Icons.JalvoroShareIcon,
  Shield: Icons.JalvoroShieldMoneyIcon,
  ShieldCheck: Icons.JalvoroShieldMoneyIcon,
  SlidersHorizontal: Icons.JalvoroFilterIcon,
  Sparkles: Icons.JalvoroSparkIcon,
  SquarePen: Icons.JalvoroEditIcon,
  Store: Icons.JalvoroBankIcon,
  Sun: Icons.JalvoroSparkIcon,
  Tag: Icons.JalvoroTagIcon,
  Target: Icons.JalvoroGoalsIcon,
  Trash: Icons.JalvoroDeleteIcon,
  Trash2: Icons.JalvoroDeleteIcon,
  TrendingDown: Icons.JalvoroTrendDownIcon,
  TrendingUp: Icons.JalvoroTrendUpIcon,
  Undo: Icons.JalvoroUndoIcon,
  Upload: Icons.JalvoroUploadIcon,
  User: Icons.JalvoroUserIcon,
  UserPlus: Icons.JalvoroUserPlusIcon,
  Users: Icons.JalvoroUsersIcon,
  Wallet: Icons.JalvoroWalletIcon,
  Wifi: Icons.JalvoroGlobeIcon,
  WifiOff: Icons.JalvoroErrorIcon,
  X: Icons.JalvoroCloseIcon,
  XCircle: Icons.JalvoroErrorIcon,
  Zap: Icons.JalvoroSparkIcon,
});

const RULES = Object.freeze([
  [/(alert|warning|triangle)/i, Icons.JalvoroWarningIcon],
  [/(error|ban|octagon|circlex|x-circle)/i, Icons.JalvoroErrorIcon],
  [/(check|success|verified|badgecheck)/i, Icons.JalvoroSuccessIcon],
  [/(info|help|question)/i, Icons.JalvoroInfoIcon],
  [/(loader|loading|pending|hourglass)/i, Icons.JalvoroPendingIcon],
  [/(search|scan|zoom)/i, Icons.JalvoroSearchIcon],
  [/(trash|delete|remove)/i, Icons.JalvoroDeleteIcon],
  [/(edit|pencil|pen|write)/i, Icons.JalvoroEditIcon],
  [/(copy|duplicate|clone)/i, Icons.JalvoroCopyIcon],
  [/(plus|add|new|create)/i, Icons.JalvoroAddIcon],
  [/(filter|funnel|sliders)/i, Icons.JalvoroFilterIcon],
  [/(sort|arrowupdown)/i, Icons.JalvoroSortIcon],
  [/(download|save)/i, Icons.JalvoroDownloadIcon],
  [/(upload|cloud)/i, Icons.JalvoroUploadIcon],
  [/(import)/i, Icons.JalvoroImportIcon],
  [/(export)/i, Icons.JalvoroExportIcon],
  [/(refresh|rotate|repeat|sync)/i, Icons.JalvoroRefreshIcon],
  [/(share|network)/i, Icons.JalvoroShareIcon],
  [/(send|plane)/i, Icons.JalvoroSendIcon],
  [/(menu|hamburger)/i, Icons.JalvoroMenuIcon],
  [/(ellipsis|more|dots)/i, Icons.JalvoroMoreIcon],
  [/(chevrondown|caretdown)/i, Icons.JalvoroChevronDownIcon],
  [/(chevronright|caretright)/i, Icons.JalvoroChevronRightIcon],
  [/(left|back|previous)/i, Icons.JalvoroArrowLeftIcon],
  [/(right|forward|next)/i, Icons.JalvoroArrowRightIcon],
  [/(up|rise|growth|increase)/i, Icons.JalvoroTrendUpIcon],
  [/(down|decline|decrease)/i, Icons.JalvoroTrendDownIcon],
  [/(dashboard|gauge|home|overview)/i, Icons.JalvoroDashboardIcon],
  [/(chart|analytics|activity|pulse|graph)/i, Icons.JalvoroAnalyticsIcon],
  [/(report|statement)/i, Icons.JalvoroReportsIcon],
  [/(brain|ai|spark|magic|wand|zap)/i, Icons.JalvoroAiInsightsIcon],
  [/(setting|cog|gear|preference)/i, Icons.JalvoroSettingsIcon],
  [/(transaction|receipt)/i, Icons.JalvoroTransactionsIcon],
  [/(wallet|purse)/i, Icons.JalvoroWalletIcon],
  [/(bank|landmark|building|institution)/i, Icons.JalvoroBankIcon],
  [/(card|payment)/i, Icons.JalvoroCardIcon],
  [/(cash|banknote|money)/i, Icons.JalvoroCashIcon],
  [/(coin|dollar|currency)/i, Icons.JalvoroCoinIcon],
  [/(invoice|bill)/i, Icons.JalvoroInvoiceIcon],
  [/(budget|pie)/i, Icons.JalvoroBudgetIcon],
  [/(saving|piggy|gift)/i, Icons.JalvoroSavingsIcon],
  [/(target|goal|milestone)/i, Icons.JalvoroGoalsIcon],
  [/(investment|portfolio|briefcase|stock)/i, Icons.JalvoroInvestmentsIcon],
  [/(tax|percent)/i, Icons.JalvoroTaxIcon],
  [/(exchange|convert|swap)/i, Icons.JalvoroExchangeIcon],
  [/(transfer)/i, Icons.JalvoroTransferIcon],
  [/(shield|secure|protect)/i, Icons.JalvoroShieldMoneyIcon],
  [/(calendar|date)/i, Icons.JalvoroCalendarIcon],
  [/(clock|time|history)/i, Icons.JalvoroClockIcon],
  [/(bell|notification)/i, Icons.JalvoroBellIcon],
  [/(folder|archive|package|box)/i, Icons.JalvoroFolderIcon],
  [/(file|document|clipboard|book|printer)/i, Icons.JalvoroFileIcon],
  [/(image|photo|picture)/i, Icons.JalvoroImageIcon],
  [/(camera)/i, Icons.JalvoroCameraIcon],
  [/(lock|privacy)/i, Icons.JalvoroLockIcon],
  [/(key|access)/i, Icons.JalvoroKeyIcon],
  [/(tag|label)/i, Icons.JalvoroTagIcon],
  [/(link|paperclip|attachment)/i, Icons.JalvoroLinkIcon],
  [/(users|team|group|contact)/i, Icons.JalvoroUsersIcon],
  [/(userplus|invite|personadd)/i, Icons.JalvoroUserPlusIcon],
  [/(user|person|profile|account)/i, Icons.JalvoroUserIcon],
  [/(mail|email|inbox)/i, Icons.JalvoroMailIcon],
  [/(message|chat|comment)/i, Icons.JalvoroChatIcon],
  [/(phone|call)/i, Icons.JalvoroPhoneIcon],
  [/(globe|world|language|wifi)/i, Icons.JalvoroGlobeIcon],
  [/(grid|layout|apps)/i, Icons.JalvoroGridIcon],
  [/(list|rows)/i, Icons.JalvoroListIcon],
  [/(sidebar|panel)/i, Icons.JalvoroSidebarIcon],
  [/(eyeoff|hidden)/i, Icons.JalvoroEyeOffIcon],
  [/(eye|view|visible)/i, Icons.JalvoroEyeIcon],
  [/(close|cancel|x)/i, Icons.JalvoroCloseIcon],
]);

const componentCache = new Map();

function resolveBase(name) {
  if (EXACT[name]) return EXACT[name];
  const rule = RULES.find(([pattern]) => pattern.test(name));
  return rule ? rule[1] : Icons.JalvoroSparkIcon;
}

function createCompatibleComponent(name) {
  if (componentCache.has(name)) return componentCache.get(name);
  const Base = resolveBase(name);
  const Component = React.forwardRef(function JalvoroLucideCompatibility(
    { absoluteStrokeWidth: _absoluteStrokeWidth, color, ...props },
    ref,
  ) {
    return React.createElement(Base, {
      ref,
      ...props,
      color,
      "data-jalvoro-source-name": name,
    });
  });
  Component.displayName = `Jalvoro${name}CompatibilityIcon`;
  componentCache.set(name, Component);
  return Component;
}

function createLucideIcon(name) {
  return createCompatibleComponent(name);
}

const target = {
  createLucideIcon,
  icons: new Proxy({}, { get: (_target, property) => createCompatibleComponent(String(property)) }),
};

module.exports = new Proxy(target, {
  get(object, property) {
    if (property === "__esModule") return true;
    if (property === "default") return module.exports;
    if (property in object) return object[property];
    return createCompatibleComponent(String(property));
  },
});
