import * as Icons from "./components";
import { JALVORO_ICON_DEFINITIONS } from "./definitions";
import { JALVORO_ICON_NAMES, type JalvoroIconName } from "./manifest";
import type { JalvoroIconComponent, JalvoroIconDefinition } from "./types";

export const jalvoroIconRegistry = {
  "dashboard": Icons.JalvoroDashboardIcon,
  "transactions": Icons.JalvoroTransactionsIcon,
  "accounts": Icons.JalvoroAccountsIcon,
  "income": Icons.JalvoroIncomeIcon,
  "expenses": Icons.JalvoroExpensesIcon,
  "goals": Icons.JalvoroGoalsIcon,
  "payables": Icons.JalvoroPayablesIcon,
  "investments": Icons.JalvoroInvestmentsIcon,
  "analytics": Icons.JalvoroAnalyticsIcon,
  "ai-insights": Icons.JalvoroAiInsightsIcon,
  "reports": Icons.JalvoroReportsIcon,
  "settings": Icons.JalvoroSettingsIcon,
  "add": Icons.JalvoroAddIcon,
  "edit": Icons.JalvoroEditIcon,
  "delete": Icons.JalvoroDeleteIcon,
  "copy": Icons.JalvoroCopyIcon,
  "search": Icons.JalvoroSearchIcon,
  "filter": Icons.JalvoroFilterIcon,
  "sort": Icons.JalvoroSortIcon,
  "share": Icons.JalvoroShareIcon,
  "export": Icons.JalvoroExportIcon,
  "import": Icons.JalvoroImportIcon,
  "download": Icons.JalvoroDownloadIcon,
  "upload": Icons.JalvoroUploadIcon,
  "refresh": Icons.JalvoroRefreshIcon,
  "check": Icons.JalvoroCheckIcon,
  "close": Icons.JalvoroCloseIcon,
  "more": Icons.JalvoroMoreIcon,
  "undo": Icons.JalvoroUndoIcon,
  "redo": Icons.JalvoroRedoIcon,
  "wallet": Icons.JalvoroWalletIcon,
  "bank": Icons.JalvoroBankIcon,
  "card": Icons.JalvoroCardIcon,
  "cash": Icons.JalvoroCashIcon,
  "coin": Icons.JalvoroCoinIcon,
  "receipt": Icons.JalvoroReceiptIcon,
  "invoice": Icons.JalvoroInvoiceIcon,
  "budget": Icons.JalvoroBudgetIcon,
  "savings": Icons.JalvoroSavingsIcon,
  "trend-up": Icons.JalvoroTrendUpIcon,
  "trend-down": Icons.JalvoroTrendDownIcon,
  "transfer": Icons.JalvoroTransferIcon,
  "exchange": Icons.JalvoroExchangeIcon,
  "calendar-money": Icons.JalvoroCalendarMoneyIcon,
  "shield-money": Icons.JalvoroShieldMoneyIcon,
  "tax": Icons.JalvoroTaxIcon,
  "file": Icons.JalvoroFileIcon,
  "folder": Icons.JalvoroFolderIcon,
  "bell": Icons.JalvoroBellIcon,
  "clock": Icons.JalvoroClockIcon,
  "calendar": Icons.JalvoroCalendarIcon,
  "tag": Icons.JalvoroTagIcon,
  "link": Icons.JalvoroLinkIcon,
  "image": Icons.JalvoroImageIcon,
  "camera": Icons.JalvoroCameraIcon,
  "lock": Icons.JalvoroLockIcon,
  "key": Icons.JalvoroKeyIcon,
  "pencil": Icons.JalvoroPencilIcon,
  "user": Icons.JalvoroUserIcon,
  "users": Icons.JalvoroUsersIcon,
  "user-plus": Icons.JalvoroUserPlusIcon,
  "mail": Icons.JalvoroMailIcon,
  "chat": Icons.JalvoroChatIcon,
  "phone": Icons.JalvoroPhoneIcon,
  "send": Icons.JalvoroSendIcon,
  "globe": Icons.JalvoroGlobeIcon,
  "menu": Icons.JalvoroMenuIcon,
  "grid": Icons.JalvoroGridIcon,
  "list": Icons.JalvoroListIcon,
  "sidebar": Icons.JalvoroSidebarIcon,
  "eye": Icons.JalvoroEyeIcon,
  "eye-off": Icons.JalvoroEyeOffIcon,
  "chevron-down": Icons.JalvoroChevronDownIcon,
  "chevron-right": Icons.JalvoroChevronRightIcon,
  "arrow-left": Icons.JalvoroArrowLeftIcon,
  "arrow-right": Icons.JalvoroArrowRightIcon,
  "success": Icons.JalvoroSuccessIcon,
  "warning": Icons.JalvoroWarningIcon,
  "info": Icons.JalvoroInfoIcon,
  "error": Icons.JalvoroErrorIcon,
  "pending": Icons.JalvoroPendingIcon,
  "spark": Icons.JalvoroSparkIcon,
} satisfies Readonly<Record<JalvoroIconName, JalvoroIconComponent>>;

export const jalvoroIconDefinitions = Object.fromEntries(
  JALVORO_ICON_DEFINITIONS.map((definition) => [definition.name, definition]),
) as unknown as Readonly<Record<JalvoroIconName, JalvoroIconDefinition>>;

const jalvoroIconNameSet = new Set<string>(JALVORO_ICON_NAMES);

export function isJalvoroIconName(value: string): value is JalvoroIconName {
  return jalvoroIconNameSet.has(value);
}
