begin;

create table if not exists private.platform_admin_invitations (
  id uuid primary key default gen_random_uuid(),
  invitation_code text not null unique default (
    'AIN-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))
  ),
  token_sha256 bytea not null unique,
  intended_email_sha256 bytea not null,
  intended_email_masked text not null,
  role text not null,
  status text not null default 'pending',
  created_by uuid not null references auth.users(id) on delete cascade,
  accepted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  accepted_at timestamptz,
  revoked_at timestamptz,
  constraint platform_admin_invitations_code_check check (
    invitation_code ~ '^AIN-[A-F0-9]{12}$'
  ),
  constraint platform_admin_invitations_token_hash_check check (
    octet_length(token_sha256) = 32
  ),
  constraint platform_admin_invitations_email_hash_check check (
    octet_length(intended_email_sha256) = 32
  ),
  constraint platform_admin_invitations_mask_check check (
    char_length(intended_email_masked) between 5 and 160
  ),
  constraint platform_admin_invitations_role_check check (
    role in ('admin', 'analyst', 'support')
  ),
  constraint platform_admin_invitations_status_check check (
    status in ('pending', 'accepted', 'revoked', 'expired')
  ),
  constraint platform_admin_invitations_expiry_check check (
    expires_at > created_at
    and expires_at <= created_at + interval '7 days'
  ),
  constraint platform_admin_invitations_acceptance_check check (
    (status = 'accepted' and accepted_at is not null and accepted_by is not null)
    or (status <> 'accepted' and accepted_at is null)
  ),
  constraint platform_admin_invitations_revocation_check check (
    (status = 'revoked' and revoked_at is not null)
    or (status <> 'revoked' and revoked_at is null)
  )
);

comment on table private.platform_admin_invitations is
  'Server-only platform administration invitations. Raw invitation secrets are never stored; intended email is retained only as a hash plus a masked display value.';

create table if not exists private.platform_admin_access_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  subject_user_id uuid references auth.users(id) on delete set null,
  invitation_id uuid references private.platform_admin_invitations(id) on delete set null,
  action text not null,
  previous_role text,
  next_role text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 months'),
  constraint platform_admin_access_audit_action_check check (
    action in (
      'invitation_created',
      'invitation_revoked',
      'invitation_accepted',
      'role_changed',
      'access_disabled',
      'access_restored'
    )
  ),
  constraint platform_admin_access_audit_previous_role_check check (
    previous_role is null or previous_role in ('owner', 'admin', 'analyst', 'support')
  ),
  constraint platform_admin_access_audit_next_role_check check (
    next_role is null or next_role in ('owner', 'admin', 'analyst', 'support')
  ),
  constraint platform_admin_access_audit_expiry_check check (
    expires_at > created_at
  )
);

comment on table private.platform_admin_access_audit is
  'Structured platform access audit. Contains no passwords, raw invitation tokens, finance content, raw IP addresses, or arbitrary metadata.';

alter table private.platform_admins enable row level security;
alter table private.platform_admin_invitations enable row level security;
alter table private.platform_admin_access_audit enable row level security;

revoke all on private.platform_admins,
  private.platform_admin_invitations,
  private.platform_admin_access_audit
  from public, anon, authenticated;
revoke all on sequence private.platform_admin_access_audit_id_seq
  from public, anon, authenticated;

drop policy if exists platform_admins_deny_direct on private.platform_admins;
create policy platform_admins_deny_direct
  on private.platform_admins
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists platform_admin_invitations_deny_direct
  on private.platform_admin_invitations;
create policy platform_admin_invitations_deny_direct
  on private.platform_admin_invitations
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists platform_admin_access_audit_deny_direct
  on private.platform_admin_access_audit;
create policy platform_admin_access_audit_deny_direct
  on private.platform_admin_access_audit
  for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete
  on private.platform_admins,
  private.platform_admin_invitations,
  private.platform_admin_access_audit
  to service_role;
grant usage, select on sequence private.platform_admin_access_audit_id_seq
  to service_role;

create index if not exists platform_admin_invitations_status_expiry_idx
  on private.platform_admin_invitations (status, expires_at, created_at desc);
create index if not exists platform_admin_invitations_email_pending_idx
  on private.platform_admin_invitations (intended_email_sha256)
  where status = 'pending';
create index if not exists platform_admin_invitations_created_by_idx
  on private.platform_admin_invitations (created_by, created_at desc);
create index if not exists platform_admin_invitations_accepted_by_idx
  on private.platform_admin_invitations (accepted_by)
  where accepted_by is not null;
create index if not exists platform_admin_access_audit_created_idx
  on private.platform_admin_access_audit (created_at desc);
create index if not exists platform_admin_access_audit_actor_idx
  on private.platform_admin_access_audit (actor_user_id, created_at desc);
create index if not exists platform_admin_access_audit_subject_idx
  on private.platform_admin_access_audit (subject_user_id, created_at desc)
  where subject_user_id is not null;
create index if not exists platform_admin_access_audit_invitation_idx
  on private.platform_admin_access_audit (invitation_id, created_at desc)
  where invitation_id is not null;
create index if not exists platform_admin_access_audit_expires_idx
  on private.platform_admin_access_audit (expires_at);

create or replace function private.mask_platform_admin_email(p_email text)
returns text
language sql
immutable
strict
set search_path = pg_catalog
as $$
  select
    case
      when position('@' in p_email) <= 1 then 'hidden'
      else
        left(split_part(lower(trim(p_email)), '@', 1), 1)
        || repeat(
          '*',
          greatest(
            2,
            least(char_length(split_part(lower(trim(p_email)), '@', 1)) - 1, 6)
          )
        )
        || '@'
        || split_part(lower(trim(p_email)), '@', 2)
    end;
$$;

revoke all on function private.mask_platform_admin_email(text)
  from public, anon, authenticated;
grant execute on function private.mask_platform_admin_email(text)
  to service_role;

create or replace function private.platform_admin_reference(p_user_id uuid)
returns text
language sql
immutable
strict
set search_path = pg_catalog, extensions
as $$
  select 'ADM-' || upper(substr(
    encode(extensions.digest(convert_to(p_user_id::text, 'UTF8'), 'sha256'), 'hex'),
    1,
    12
  ));
$$;

revoke all on function private.platform_admin_reference(uuid)
  from public, anon, authenticated;
grant execute on function private.platform_admin_reference(uuid)
  to service_role;

create or replace function private.create_platform_admin_invitation(
  p_email text,
  p_role text,
  p_token_sha256 text,
  p_expires_in_hours integer default 72
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private, extensions
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_email text := lower(trim(coalesce(p_email, '')));
  v_email_hash bytea;
  v_token_hash bytea;
  v_invitation private.platform_admin_invitations%rowtype;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role <> 'owner' then
    raise exception 'owner_access_required' using errcode = '42501';
  end if;

  if char_length(v_email) < 5
    or char_length(v_email) > 254
    or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'admin_invitation_email_invalid' using errcode = '22023';
  end if;

  if p_role not in ('admin', 'analyst', 'support') then
    raise exception 'admin_invitation_role_invalid' using errcode = '22023';
  end if;

  if p_expires_in_hours < 1 or p_expires_in_hours > 168 then
    raise exception 'admin_invitation_expiry_invalid' using errcode = '22023';
  end if;

  if p_token_sha256 !~ '^[a-f0-9]{64}$' then
    raise exception 'admin_invitation_token_invalid' using errcode = '22023';
  end if;

  v_email_hash := extensions.digest(convert_to(v_email, 'UTF8'), 'sha256');
  v_token_hash := decode(p_token_sha256, 'hex');

  update private.platform_admin_invitations
  set status = 'expired'
  where status = 'pending' and expires_at <= now();

  update private.platform_admin_invitations
  set status = 'revoked', revoked_at = now()
  where status = 'pending'
    and intended_email_sha256 = v_email_hash;

  insert into private.platform_admin_invitations (
    token_sha256,
    intended_email_sha256,
    intended_email_masked,
    role,
    created_by,
    expires_at
  ) values (
    v_token_hash,
    v_email_hash,
    private.mask_platform_admin_email(v_email),
    p_role,
    v_actor,
    now() + make_interval(hours => p_expires_in_hours)
  ) returning * into v_invitation;

  insert into private.platform_admin_access_audit (
    actor_user_id,
    invitation_id,
    action,
    next_role
  ) values (
    v_actor,
    v_invitation.id,
    'invitation_created',
    v_invitation.role
  );

  return jsonb_build_object(
    'invitationCode', v_invitation.invitation_code,
    'maskedEmail', v_invitation.intended_email_masked,
    'role', v_invitation.role,
    'expiresAt', v_invitation.expires_at
  );
end;
$$;

create or replace function public.create_platform_admin_invitation(
  p_email text,
  p_role text,
  p_token_sha256 text,
  p_expires_in_hours integer default 72
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.create_platform_admin_invitation(
    p_email,
    p_role,
    p_token_sha256,
    p_expires_in_hours
  );
$$;

revoke all on function private.create_platform_admin_invitation(text, text, text, integer)
  from public, anon;
grant execute on function private.create_platform_admin_invitation(text, text, text, integer)
  to authenticated;
revoke all on function public.create_platform_admin_invitation(text, text, text, integer)
  from public, anon;
grant execute on function public.create_platform_admin_invitation(text, text, text, integer)
  to authenticated;

create or replace function private.accept_platform_admin_invitation(
  p_token_sha256 text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private, extensions
as $$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_email_hash bytea;
  v_token_hash bytea;
  v_invitation private.platform_admin_invitations%rowtype;
  v_existing_role text;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  if p_token_sha256 !~ '^[a-f0-9]{64}$' then
    raise exception 'admin_invitation_token_invalid' using errcode = '22023';
  end if;

  select lower(trim(email)) into v_email
  from auth.users
  where id = v_user_id and deleted_at is null;

  if v_email is null or v_email = '' then
    raise exception 'verified_email_required' using errcode = '42501';
  end if;

  v_email_hash := extensions.digest(convert_to(v_email, 'UTF8'), 'sha256');
  v_token_hash := decode(p_token_sha256, 'hex');

  update private.platform_admin_invitations
  set status = 'expired'
  where status = 'pending' and expires_at <= now();

  select * into v_invitation
  from private.platform_admin_invitations
  where token_sha256 = v_token_hash
    and intended_email_sha256 = v_email_hash
    and status = 'pending'
    and expires_at > now()
  for update;

  if not found then
    raise exception 'admin_invitation_not_found' using errcode = 'P0002';
  end if;

  select role into v_existing_role
  from private.platform_admins
  where user_id = v_user_id and disabled_at is null;

  if v_existing_role = 'owner' then
    raise exception 'owner_role_protected' using errcode = '42501';
  end if;

  insert into private.platform_admins (
    user_id,
    role,
    created_by,
    disabled_at
  ) values (
    v_user_id,
    v_invitation.role,
    v_invitation.created_by,
    null
  )
  on conflict (user_id) do update
  set role = excluded.role,
      created_by = excluded.created_by,
      disabled_at = null;

  update private.platform_admin_invitations
  set status = 'accepted',
      accepted_by = v_user_id,
      accepted_at = now()
  where id = v_invitation.id;

  insert into private.platform_admin_access_audit (
    actor_user_id,
    subject_user_id,
    invitation_id,
    action,
    previous_role,
    next_role
  ) values (
    v_user_id,
    v_user_id,
    v_invitation.id,
    'invitation_accepted',
    v_existing_role,
    v_invitation.role
  );

  return jsonb_build_object(
    'accepted', true,
    'role', v_invitation.role,
    'redirectTo', '/admin'
  );
end;
$$;

create or replace function public.accept_platform_admin_invitation(
  p_token_sha256 text
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.accept_platform_admin_invitation(p_token_sha256);
$$;

revoke all on function private.accept_platform_admin_invitation(text)
  from public, anon;
grant execute on function private.accept_platform_admin_invitation(text)
  to authenticated;
revoke all on function public.accept_platform_admin_invitation(text)
  from public, anon;
grant execute on function public.accept_platform_admin_invitation(text)
  to authenticated;

create or replace function private.revoke_platform_admin_invitation(
  p_invitation_code text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_invitation private.platform_admin_invitations%rowtype;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role <> 'owner' then
    raise exception 'owner_access_required' using errcode = '42501';
  end if;

  select * into v_invitation
  from private.platform_admin_invitations
  where invitation_code = upper(trim(p_invitation_code))
    and status = 'pending'
  for update;

  if not found then
    raise exception 'admin_invitation_not_found' using errcode = 'P0002';
  end if;

  update private.platform_admin_invitations
  set status = 'revoked', revoked_at = now()
  where id = v_invitation.id;

  insert into private.platform_admin_access_audit (
    actor_user_id,
    invitation_id,
    action,
    previous_role
  ) values (
    v_actor,
    v_invitation.id,
    'invitation_revoked',
    v_invitation.role
  );

  return jsonb_build_object(
    'revoked', true,
    'invitationCode', v_invitation.invitation_code
  );
end;
$$;

create or replace function public.revoke_platform_admin_invitation(
  p_invitation_code text
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.revoke_platform_admin_invitation(p_invitation_code);
$$;

revoke all on function private.revoke_platform_admin_invitation(text)
  from public, anon;
grant execute on function private.revoke_platform_admin_invitation(text)
  to authenticated;
revoke all on function public.revoke_platform_admin_invitation(text)
  from public, anon;
grant execute on function public.revoke_platform_admin_invitation(text)
  to authenticated;

create or replace function private.apply_platform_admin_member_action(
  p_admin_reference text,
  p_action text,
  p_role text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_target private.platform_admins%rowtype;
  v_target_reference text := upper(trim(coalesce(p_admin_reference, '')));
  v_next_role text;
  v_active_owner_count bigint;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role <> 'owner' then
    raise exception 'owner_access_required' using errcode = '42501';
  end if;

  select pa.* into v_target
  from private.platform_admins pa
  where private.platform_admin_reference(pa.user_id) = v_target_reference
  for update;

  if not found then
    raise exception 'admin_member_not_found' using errcode = 'P0002';
  end if;

  if v_target.user_id = v_actor then
    raise exception 'admin_self_change_blocked' using errcode = '42501';
  end if;

  select count(*)::bigint into v_active_owner_count
  from private.platform_admins
  where role = 'owner' and disabled_at is null;

  if p_action = 'set_role' then
    if p_role not in ('owner', 'admin', 'analyst', 'support') then
      raise exception 'admin_role_invalid' using errcode = '22023';
    end if;

    if v_target.role = 'owner'
      and v_target.disabled_at is null
      and p_role <> 'owner'
      and v_active_owner_count <= 1 then
      raise exception 'last_owner_protected' using errcode = '42501';
    end if;

    v_next_role := p_role;
    update private.platform_admins
    set role = v_next_role
    where user_id = v_target.user_id;

    insert into private.platform_admin_access_audit (
      actor_user_id,
      subject_user_id,
      action,
      previous_role,
      next_role
    ) values (
      v_actor,
      v_target.user_id,
      'role_changed',
      v_target.role,
      v_next_role
    );

  elsif p_action = 'disable' then
    if v_target.disabled_at is not null then
      raise exception 'admin_already_disabled' using errcode = '22023';
    end if;

    if v_target.role = 'owner' and v_active_owner_count <= 1 then
      raise exception 'last_owner_protected' using errcode = '42501';
    end if;

    update private.platform_admins
    set disabled_at = now()
    where user_id = v_target.user_id;

    insert into private.platform_admin_access_audit (
      actor_user_id,
      subject_user_id,
      action,
      previous_role
    ) values (
      v_actor,
      v_target.user_id,
      'access_disabled',
      v_target.role
    );

  elsif p_action = 'restore' then
    if v_target.disabled_at is null then
      raise exception 'admin_already_active' using errcode = '22023';
    end if;

    update private.platform_admins
    set disabled_at = null
    where user_id = v_target.user_id;

    insert into private.platform_admin_access_audit (
      actor_user_id,
      subject_user_id,
      action,
      next_role
    ) values (
      v_actor,
      v_target.user_id,
      'access_restored',
      v_target.role
    );
  else
    raise exception 'admin_action_invalid' using errcode = '22023';
  end if;

  return jsonb_build_object(
    'adminReference', v_target_reference,
    'action', p_action,
    'role', coalesce(v_next_role, v_target.role)
  );
end;
$$;

create or replace function public.apply_platform_admin_member_action(
  p_admin_reference text,
  p_action text,
  p_role text default null
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.apply_platform_admin_member_action(
    p_admin_reference,
    p_action,
    p_role
  );
$$;

revoke all on function private.apply_platform_admin_member_action(text, text, text)
  from public, anon;
grant execute on function private.apply_platform_admin_member_action(text, text, text)
  to authenticated;
revoke all on function public.apply_platform_admin_member_action(text, text, text)
  from public, anon;
grant execute on function public.apply_platform_admin_member_action(text, text, text)
  to authenticated;

create or replace function private.get_admin_access_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role is null then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'operationsAllowed', v_actor_role = 'owner',
    'inviteDelivery', 'manual_code',
    'rawInviteTokenStored', false,
    'userMetadataAuthorization', false,
    'serviceRoleExposedToBrowser', false,
    'counts', jsonb_build_object(
      'activeOwners', (
        select count(*)::bigint from private.platform_admins
        where role = 'owner' and disabled_at is null
      ),
      'activeAdmins', (
        select count(*)::bigint from private.platform_admins
        where role = 'admin' and disabled_at is null
      ),
      'activeAnalysts', (
        select count(*)::bigint from private.platform_admins
        where role = 'analyst' and disabled_at is null
      ),
      'activeSupport', (
        select count(*)::bigint from private.platform_admins
        where role = 'support' and disabled_at is null
      ),
      'disabledMembers', (
        select count(*)::bigint from private.platform_admins
        where disabled_at is not null
      ),
      'pendingInvitations', (
        select count(*)::bigint from private.platform_admin_invitations
        where status = 'pending' and expires_at > now()
      )
    ),
    'members', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'adminReference', private.platform_admin_reference(rows.user_id),
          'maskedEmail', private.mask_platform_admin_email(rows.email),
          'role', rows.role,
          'status', case when rows.disabled_at is null then 'active' else 'disabled' end,
          'createdAt', rows.created_at,
          'lastAccessAt', rows.last_access_at,
          'isSelf', rows.user_id = v_actor,
          'manageable', v_actor_role = 'owner' and rows.user_id <> v_actor
        ) order by
          case rows.role when 'owner' then 1 when 'admin' then 2 when 'analyst' then 3 else 4 end,
          rows.created_at
      )
      from (
        select
          pa.user_id,
          au.email,
          pa.role,
          pa.created_at,
          pa.disabled_at,
          (
            select max(aal.created_at)
            from private.admin_access_log aal
            where aal.admin_user_id = pa.user_id
          ) as last_access_at
        from private.platform_admins pa
        join auth.users au on au.id = pa.user_id
        where au.deleted_at is null
        order by pa.created_at
        limit 50
      ) rows
    ), '[]'::jsonb),
    'invitations', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'invitationCode', invitation_code,
          'maskedEmail', intended_email_masked,
          'role', role,
          'status', case when expires_at <= now() then 'expired' else status end,
          'createdAt', created_at,
          'expiresAt', expires_at,
          'manageable', v_actor_role = 'owner' and status = 'pending' and expires_at > now()
        ) order by created_at desc
      )
      from (
        select *
        from private.platform_admin_invitations
        where status = 'pending'
        order by created_at desc
        limit 30
      ) invites
    ), '[]'::jsonb),
    'recentEvents', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'eventReference', 'AAE-' || lpad(event_id::text, 10, '0'),
          'action', action,
          'actorReference', private.platform_admin_reference(actor_user_id),
          'subjectReference', case
            when subject_user_id is null then null
            else private.platform_admin_reference(subject_user_id)
          end,
          'invitationCode', invitation_code,
          'previousRole', previous_role,
          'nextRole', next_role,
          'createdAt', created_at
        ) order by created_at desc
      )
      from (
        select
          paa.id as event_id,
          paa.action,
          paa.actor_user_id,
          paa.subject_user_id,
          pai.invitation_code,
          paa.previous_role,
          paa.next_role,
          paa.created_at
        from private.platform_admin_access_audit paa
        left join private.platform_admin_invitations pai on pai.id = paa.invitation_id
        order by paa.created_at desc
        limit 30
      ) events
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function private.get_admin_access_snapshot()
  from public, anon;
grant execute on function private.get_admin_access_snapshot()
  to authenticated;

create or replace function public.get_platform_admin_snapshot()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.get_platform_admin_snapshot()
    || jsonb_build_object('access', private.get_admin_access_snapshot());
$$;

revoke all on function public.get_platform_admin_snapshot()
  from public, anon;
grant execute on function public.get_platform_admin_snapshot()
  to authenticated;

create or replace function private.purge_expired_admin_access_data(
  p_initiated_by text default 'service_role'
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
declare
  v_audit_deleted bigint := 0;
  v_invites_deleted bigint := 0;
begin
  if p_initiated_by not in ('scheduled', 'service_role', 'manual') then
    raise exception 'admin_access_retention_initiator_invalid' using errcode = '22023';
  end if;

  delete from private.platform_admin_access_audit
  where expires_at <= now();
  get diagnostics v_audit_deleted = row_count;

  delete from private.platform_admin_invitations
  where (
    status in ('accepted', 'revoked', 'expired')
    and created_at <= now() - interval '24 months'
  ) or (
    status = 'pending'
    and expires_at <= now() - interval '30 days'
  );
  get diagnostics v_invites_deleted = row_count;

  return jsonb_build_object(
    'auditEventsDeleted', v_audit_deleted,
    'invitationsDeleted', v_invites_deleted,
    'ranAt', now()
  );
end;
$$;

revoke all on function private.purge_expired_admin_access_data(text)
  from public, anon, authenticated;
grant execute on function private.purge_expired_admin_access_data(text)
  to service_role;

comment on function public.create_platform_admin_invitation(text, text, text, integer) is
  'Owner-only platform admin invitation creation. Accepts an intended email and a server-generated SHA-256 token hash; raw invitation tokens are never stored.';
comment on function public.accept_platform_admin_invitation(text) is
  'Authenticated invitation acceptance. The signed-in account email must match the invitation email hash.';
comment on function public.apply_platform_admin_member_action(text, text, text) is
  'Owner-only structured role, disable and restore operations. Self-change and last-owner lockout are rejected.';

commit;
