begin;

create schema if not exists telemetry;

revoke all on schema telemetry from public, anon, authenticated;
grant usage on schema telemetry to service_role;

create table if not exists telemetry.subjects (
  user_id uuid primary key references auth.users(id) on delete cascade,
  subject_id uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

comment on table telemetry.subjects is
  'Private mapping between an authenticated account and a random telemetry subject identifier. Never expose through the Data API or analytics UI.';

create table if not exists telemetry.events (
  id bigint generated by default as identity primary key,
  subject_id uuid not null references telemetry.subjects(subject_id) on delete cascade,
  session_id uuid not null,
  event_name text not null,
  route text not null,
  feature text,
  result text,
  navigation_type text,
  metric_name text,
  metric_value double precision,
  metric_rating text,
  country_code text,
  region_code text,
  city text,
  device_type text not null,
  os_family text not null,
  browser_family text not null,
  request_id text,
  app_version text,
  occurred_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  constraint telemetry_events_event_name_check check (
    event_name in (
      'page_view',
      'page_navigation',
      'web_vital',
      'long_task',
      'feature_used',
      'operation_started',
      'operation_completed',
      'operation_failed'
    )
  ),
  constraint telemetry_events_route_check check (
    char_length(route) between 1 and 160
    and route like '/%'
    and route !~ '[?#]'
  ),
  constraint telemetry_events_feature_check check (
    feature is null or feature in (
      'dashboard',
      'transactions',
      'income',
      'expenses',
      'accounts',
      'goals',
      'payables',
      'investments',
      'analytics',
      'reports',
      'settings',
      'import',
      'export',
      'authentication',
      'onboarding',
      'ai_insights',
      'business'
    )
  ),
  constraint telemetry_events_result_check check (
    result is null or result in ('success', 'failure', 'cancelled', 'unknown')
  ),
  constraint telemetry_events_navigation_type_check check (
    navigation_type is null or navigation_type in ('push', 'replace', 'traverse', 'reload')
  ),
  constraint telemetry_events_metric_name_check check (
    metric_name is null or metric_name in ('TTFB', 'FCP', 'LCP', 'CLS', 'LOAD', 'LONG_TASK')
  ),
  constraint telemetry_events_metric_value_check check (
    metric_value is null or (metric_value >= 0 and metric_value <= 600000)
  ),
  constraint telemetry_events_metric_rating_check check (
    metric_rating is null or metric_rating in ('good', 'needs-improvement', 'poor', 'unrated')
  ),
  constraint telemetry_events_country_check check (
    country_code is null or country_code ~ '^[A-Z]{2}$'
  ),
  constraint telemetry_events_region_check check (
    region_code is null or region_code ~ '^[A-Z0-9-]{1,8}$'
  ),
  constraint telemetry_events_city_check check (
    city is null or char_length(city) <= 80
  ),
  constraint telemetry_events_device_check check (
    device_type in ('mobile', 'tablet', 'desktop', 'unknown')
  ),
  constraint telemetry_events_os_check check (
    os_family in ('Android', 'iOS', 'Windows', 'macOS', 'Linux', 'Other')
  ),
  constraint telemetry_events_browser_check check (
    browser_family in ('Chrome', 'Edge', 'Firefox', 'Opera', 'Safari', 'Samsung Internet', 'Other')
  ),
  constraint telemetry_events_request_id_check check (
    request_id is null or char_length(request_id) <= 128
  ),
  constraint telemetry_events_app_version_check check (
    app_version is null or char_length(app_version) <= 64
  )
);

comment on table telemetry.events is
  'Privacy-minimised product and performance telemetry. Contains no raw IP address, email, finance value, free-form user input, URL query string, or exact device model.';

alter table telemetry.subjects enable row level security;
alter table telemetry.events enable row level security;

revoke all on telemetry.subjects from public, anon, authenticated;
revoke all on telemetry.events from public, anon, authenticated;

grant select, update, delete on telemetry.subjects to service_role;
grant select, delete on telemetry.events to service_role;
grant usage, select on sequence telemetry.events_id_seq to service_role;

create index if not exists telemetry_events_occurred_at_idx
  on telemetry.events (occurred_at desc);
create index if not exists telemetry_events_subject_occurred_idx
  on telemetry.events (subject_id, occurred_at desc);
create index if not exists telemetry_events_name_occurred_idx
  on telemetry.events (event_name, occurred_at desc);
create index if not exists telemetry_events_route_occurred_idx
  on telemetry.events (route, occurred_at desc);
create index if not exists telemetry_events_country_city_occurred_idx
  on telemetry.events (country_code, city, occurred_at desc);
create index if not exists telemetry_events_expires_at_idx
  on telemetry.events (expires_at);

create or replace function public.record_privacy_telemetry_event(
  p_session_id uuid,
  p_event_name text,
  p_route text,
  p_feature text default null,
  p_result text default null,
  p_navigation_type text default null,
  p_metric_name text default null,
  p_metric_value double precision default null,
  p_metric_rating text default null,
  p_country_code text default null,
  p_region_code text default null,
  p_city text default null,
  p_device_type text default 'unknown',
  p_os_family text default 'Other',
  p_browser_family text default 'Other',
  p_request_id text default null,
  p_app_version text default null
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, auth, telemetry
as $$
declare
  v_user_id uuid := auth.uid();
  v_subject_id uuid;
  v_event_name text := lower(btrim(coalesce(p_event_name, '')));
  v_route text := btrim(coalesce(p_route, ''));
  v_feature text := nullif(lower(btrim(coalesce(p_feature, ''))), '');
  v_result text := nullif(lower(btrim(coalesce(p_result, ''))), '');
  v_navigation_type text := nullif(lower(btrim(coalesce(p_navigation_type, ''))), '');
  v_metric_name text := nullif(upper(btrim(coalesce(p_metric_name, ''))), '');
  v_metric_rating text := nullif(lower(btrim(coalesce(p_metric_rating, ''))), '');
  v_country_code text := nullif(upper(btrim(coalesce(p_country_code, ''))), '');
  v_region_code text := nullif(upper(btrim(coalesce(p_region_code, ''))), '');
  v_city text := nullif(btrim(coalesce(p_city, '')), '');
  v_device_type text := lower(btrim(coalesce(p_device_type, 'unknown')));
  v_os_family text := btrim(coalesce(p_os_family, 'Other'));
  v_browser_family text := btrim(coalesce(p_browser_family, 'Other'));
  v_request_id text := nullif(btrim(coalesce(p_request_id, '')), '');
  v_app_version text := nullif(btrim(coalesce(p_app_version, '')), '');
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  if p_session_id is null then
    raise exception 'session_id_required' using errcode = '22023';
  end if;

  if v_event_name not in (
    'page_view',
    'page_navigation',
    'web_vital',
    'long_task',
    'feature_used',
    'operation_started',
    'operation_completed',
    'operation_failed'
  ) then
    raise exception 'telemetry_event_invalid' using errcode = '22023';
  end if;

  if char_length(v_route) < 1
     or char_length(v_route) > 160
     or v_route not like '/%'
     or v_route ~ '[?#]' then
    raise exception 'telemetry_route_invalid' using errcode = '22023';
  end if;

  if v_event_name in ('feature_used', 'operation_started', 'operation_completed', 'operation_failed')
     and v_feature is null then
    raise exception 'telemetry_feature_required' using errcode = '22023';
  end if;

  if v_event_name in ('web_vital', 'long_task')
     and (v_metric_name is null or p_metric_value is null) then
    raise exception 'telemetry_metric_required' using errcode = '22023';
  end if;

  insert into telemetry.subjects (user_id)
  values (v_user_id)
  on conflict (user_id) do update
    set last_seen_at = now()
  returning subject_id into v_subject_id;

  insert into telemetry.events (
    subject_id,
    session_id,
    event_name,
    route,
    feature,
    result,
    navigation_type,
    metric_name,
    metric_value,
    metric_rating,
    country_code,
    region_code,
    city,
    device_type,
    os_family,
    browser_family,
    request_id,
    app_version
  )
  values (
    v_subject_id,
    p_session_id,
    v_event_name,
    v_route,
    v_feature,
    v_result,
    v_navigation_type,
    v_metric_name,
    p_metric_value,
    v_metric_rating,
    v_country_code,
    v_region_code,
    v_city,
    v_device_type,
    v_os_family,
    v_browser_family,
    v_request_id,
    v_app_version
  );
end;
$$;

revoke all on function public.record_privacy_telemetry_event(
  uuid,
  text,
  text,
  text,
  text,
  text,
  text,
  double precision,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) from public, anon;

grant execute on function public.record_privacy_telemetry_event(
  uuid,
  text,
  text,
  text,
  text,
  text,
  text,
  double precision,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) to authenticated;

create or replace function telemetry.purge_expired_events()
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, telemetry
as $$
declare
  v_deleted bigint;
begin
  delete from telemetry.events
   where expires_at <= now();
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function telemetry.purge_expired_events() from public, anon, authenticated;
grant execute on function telemetry.purge_expired_events() to service_role;

commit;
