begin;

create table if not exists private.privacy_request_audit (
  id bigint generated by default as identity primary key,
  request_id uuid not null references private.privacy_requests(id) on delete cascade,
  actor_admin_user_id uuid references auth.users(id) on delete set null,
  action text not null default 'workflow_updated',
  previous_status text not null,
  next_status text not null,
  previous_verification_status text not null,
  next_verification_status text not null,
  assignment_changed boolean not null default false,
  previous_due_at timestamptz,
  next_due_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 months'),
  constraint privacy_request_audit_action_check check (
    action in ('workflow_updated', 'claimed_and_updated')
  ),
  constraint privacy_request_audit_status_check check (
    previous_status in (
      'pending', 'identity_verification', 'in_progress',
      'completed', 'rejected', 'cancelled'
    )
    and next_status in (
      'pending', 'identity_verification', 'in_progress',
      'completed', 'rejected', 'cancelled'
    )
  ),
  constraint privacy_request_audit_verification_check check (
    previous_verification_status in ('not_started', 'pending', 'verified', 'failed')
    and next_verification_status in ('not_started', 'pending', 'verified', 'failed')
  )
);

comment on table private.privacy_request_audit is
  'Structured server-only audit of privacy workflow transitions. Contains no request message, end-user identity, finance content, raw IP address, or payment credential.';

alter table private.privacy_request_audit enable row level security;
revoke all on private.privacy_request_audit from public, anon, authenticated;
revoke all on sequence private.privacy_request_audit_id_seq
  from public, anon, authenticated;

drop policy if exists privacy_request_audit_deny_direct
  on private.privacy_request_audit;
create policy privacy_request_audit_deny_direct
  on private.privacy_request_audit
  for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete
  on private.privacy_request_audit
  to service_role;
grant usage, select on sequence private.privacy_request_audit_id_seq
  to service_role;

create index if not exists privacy_request_audit_request_created_idx
  on private.privacy_request_audit (request_id, created_at desc);
create index if not exists privacy_request_audit_actor_created_idx
  on private.privacy_request_audit (actor_admin_user_id, created_at desc)
  where actor_admin_user_id is not null;
create index if not exists privacy_request_audit_expires_at_idx
  on private.privacy_request_audit (expires_at);

alter table private.privacy_retention_runs
  add column if not exists request_audit_logs_deleted bigint not null default 0;

alter table private.privacy_retention_runs
  drop constraint if exists privacy_retention_runs_counts_check;
alter table private.privacy_retention_runs
  add constraint privacy_retention_runs_counts_check check (
    telemetry_events_deleted >= 0
    and admin_access_logs_deleted >= 0
    and prior_retention_runs_deleted >= 0
    and request_audit_logs_deleted >= 0
  );

create or replace function private.apply_privacy_request_workflow(
  p_request_code text,
  p_status text,
  p_verification_status text,
  p_due_date date default null,
  p_assign_to_self boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_admin_user_id uuid := auth.uid();
  v_admin_role text;
  v_request private.privacy_requests%rowtype;
  v_next_due_at timestamptz;
  v_assignment_changed boolean := false;
begin
  select role
  into v_admin_role
  from private.platform_admins
  where user_id = v_admin_user_id
    and disabled_at is null;

  if v_admin_user_id is null or v_admin_role not in ('owner', 'admin') then
    raise exception 'privacy_request_management_required' using errcode = '42501';
  end if;

  if p_request_code is null or p_request_code !~ '^PRV-[A-F0-9]{12}$' then
    raise exception 'privacy_request_code_invalid' using errcode = '22023';
  end if;

  if p_status not in (
    'pending', 'identity_verification', 'in_progress',
    'completed', 'rejected', 'cancelled'
  ) then
    raise exception 'privacy_request_status_invalid' using errcode = '22023';
  end if;

  if p_verification_status not in ('not_started', 'pending', 'verified', 'failed') then
    raise exception 'privacy_request_verification_invalid' using errcode = '22023';
  end if;

  select *
  into v_request
  from private.privacy_requests
  where request_code = p_request_code
  for update;

  if not found then
    raise exception 'privacy_request_not_found' using errcode = 'P0002';
  end if;

  if v_request.assigned_admin_user_id is not null
     and v_request.assigned_admin_user_id <> v_admin_user_id
     and v_admin_role <> 'owner' then
    raise exception 'privacy_request_assigned_elsewhere' using errcode = '42501';
  end if;

  if p_status = 'completed' and p_verification_status <> 'verified' then
    raise exception 'privacy_request_verification_required' using errcode = '22023';
  end if;

  if p_due_date is not null and p_due_date < v_request.created_at::date then
    raise exception 'privacy_request_due_date_invalid' using errcode = '22023';
  end if;

  if p_due_date is not null then
    v_next_due_at := (p_due_date::timestamptz + interval '1 day' - interval '1 second');
  end if;

  v_assignment_changed := p_assign_to_self
    and v_request.assigned_admin_user_id is distinct from v_admin_user_id;

  update private.privacy_requests
  set status = p_status,
      verification_status = p_verification_status,
      due_at = v_next_due_at,
      assigned_admin_user_id = case
        when p_assign_to_self then v_admin_user_id
        else assigned_admin_user_id
      end,
      closed_at = case
        when p_status in ('completed', 'rejected', 'cancelled')
          then coalesce(closed_at, now())
        else null
      end,
      updated_at = now()
  where id = v_request.id;

  insert into private.privacy_request_audit (
    request_id,
    actor_admin_user_id,
    action,
    previous_status,
    next_status,
    previous_verification_status,
    next_verification_status,
    assignment_changed,
    previous_due_at,
    next_due_at
  )
  values (
    v_request.id,
    v_admin_user_id,
    case when v_assignment_changed
      then 'claimed_and_updated'
      else 'workflow_updated'
    end,
    v_request.status,
    p_status,
    v_request.verification_status,
    p_verification_status,
    v_assignment_changed,
    v_request.due_at,
    v_next_due_at
  );

  return jsonb_build_object(
    'requestCode', v_request.request_code,
    'status', p_status,
    'verificationStatus', p_verification_status,
    'dueAt', v_next_due_at,
    'assignedToMe', (
      p_assign_to_self or v_request.assigned_admin_user_id = v_admin_user_id
    ),
    'updatedAt', now()
  );
end;
$$;

revoke all on function private.apply_privacy_request_workflow(
  text, text, text, date, boolean
) from public, anon;
grant execute on function private.apply_privacy_request_workflow(
  text, text, text, date, boolean
) to authenticated;

create or replace function public.apply_privacy_request_workflow(
  p_request_code text,
  p_status text,
  p_verification_status text,
  p_due_date date default null,
  p_assign_to_self boolean default false
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.apply_privacy_request_workflow(
    p_request_code,
    p_status,
    p_verification_status,
    p_due_date,
    p_assign_to_self
  );
$$;

revoke all on function public.apply_privacy_request_workflow(
  text, text, text, date, boolean
) from public, anon;
grant execute on function public.apply_privacy_request_workflow(
  text, text, text, date, boolean
) to authenticated;

create or replace function private.purge_expired_privacy_operational_data(
  p_initiated_by text default 'service_role',
  p_actor_admin_user_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, private, telemetry
as $$
declare
  v_telemetry_deleted bigint := 0;
  v_admin_logs_deleted bigint := 0;
  v_request_audit_deleted bigint := 0;
  v_old_runs_deleted bigint := 0;
begin
  if p_initiated_by not in ('scheduled', 'service_role', 'manual') then
    raise exception 'privacy_retention_initiator_invalid' using errcode = '22023';
  end if;

  delete from telemetry.events
  where expires_at <= now();
  get diagnostics v_telemetry_deleted = row_count;

  delete from private.admin_access_log
  where expires_at <= now();
  get diagnostics v_admin_logs_deleted = row_count;

  delete from private.privacy_request_audit
  where expires_at <= now();
  get diagnostics v_request_audit_deleted = row_count;

  delete from private.privacy_retention_runs
  where expires_at <= now();
  get diagnostics v_old_runs_deleted = row_count;

  insert into private.privacy_retention_runs (
    initiated_by,
    actor_admin_user_id,
    telemetry_events_deleted,
    admin_access_logs_deleted,
    request_audit_logs_deleted,
    prior_retention_runs_deleted
  )
  values (
    p_initiated_by,
    p_actor_admin_user_id,
    v_telemetry_deleted,
    v_admin_logs_deleted,
    v_request_audit_deleted,
    v_old_runs_deleted
  );

  return jsonb_build_object(
    'telemetryEventsDeleted', v_telemetry_deleted,
    'adminAccessLogsDeleted', v_admin_logs_deleted,
    'requestAuditLogsDeleted', v_request_audit_deleted,
    'priorRetentionRunsDeleted', v_old_runs_deleted,
    'ranAt', now()
  );
end;
$$;

revoke all on function private.purge_expired_privacy_operational_data(text, uuid)
  from public, anon, authenticated;
grant execute on function private.purge_expired_privacy_operational_data(text, uuid)
  to service_role;

create or replace function private.get_privacy_governance_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private, telemetry
as $$
declare
  v_admin_user_id uuid := auth.uid();
  v_admin_role text;
  v_last_run private.privacy_retention_runs%rowtype;
begin
  select role
  into v_admin_role
  from private.platform_admins
  where user_id = v_admin_user_id
    and disabled_at is null;

  if v_admin_user_id is null or v_admin_role is null then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  select *
  into v_last_run
  from private.privacy_retention_runs
  order by ran_at desc
  limit 1;

  return jsonb_build_object(
    'openRequests', (
      select count(*)::bigint
      from private.privacy_requests
      where status in ('pending', 'identity_verification', 'in_progress')
    ),
    'overdueRequests', (
      select count(*)::bigint
      from private.privacy_requests
      where status in ('pending', 'identity_verification', 'in_progress')
        and due_at is not null
        and due_at < now()
    ),
    'completedRequests30d', (
      select count(*)::bigint
      from private.privacy_requests
      where status = 'completed'
        and closed_at >= now() - interval '30 days'
    ),
    'requestAuditEvents30d', (
      select count(*)::bigint
      from private.privacy_request_audit
      where created_at >= now() - interval '30 days'
    ),
    'requestOperationsAllowed', v_admin_role in ('owner', 'admin'),
    'requestQueue', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'requestCode', queue.request_code,
          'requestType', queue.request_type,
          'status', queue.status,
          'verificationStatus', queue.verification_status,
          'source', queue.source,
          'createdAt', queue.created_at,
          'dueAt', queue.due_at,
          'assigned', queue.assigned_admin_user_id is not null,
          'assignedToMe', queue.assigned_admin_user_id = v_admin_user_id,
          'overdue', queue.due_at is not null and queue.due_at < now(),
          'manageable', (
            v_admin_role = 'owner'
            or queue.assigned_admin_user_id is null
            or queue.assigned_admin_user_id = v_admin_user_id
          )
        ) order by
          (queue.due_at is not null and queue.due_at < now()) desc,
          queue.due_at asc nulls last,
          queue.created_at asc
      )
      from (
        select
          request_code,
          request_type,
          status,
          verification_status,
          source,
          assigned_admin_user_id,
          created_at,
          due_at
        from private.privacy_requests
        where status in ('pending', 'identity_verification', 'in_progress')
        order by
          (due_at is not null and due_at < now()) desc,
          due_at asc nulls last,
          created_at asc
        limit 30
      ) as queue
    ), '[]'::jsonb),
    'adminViews30d', (
      select count(*)::bigint
      from private.admin_access_log
      where created_at >= now() - interval '30 days'
    ),
    'telemetryEventsStored', (
      select count(*)::bigint from telemetry.events
    ),
    'telemetrySubjectsStored', (
      select count(*)::bigint from telemetry.subjects
    ),
    'expiredTelemetryPending', (
      select count(*)::bigint
      from telemetry.events
      where expires_at <= now()
    ),
    'expiredAdminAuditPending', (
      select count(*)::bigint
      from private.admin_access_log
      where expires_at <= now()
    ),
    'expiredRequestAuditPending', (
      select count(*)::bigint
      from private.privacy_request_audit
      where expires_at <= now()
    ),
    'lastRetentionRunAt', v_last_run.ran_at,
    'lastRetentionRowsDeleted', coalesce(
      v_last_run.telemetry_events_deleted
      + v_last_run.admin_access_logs_deleted
      + v_last_run.request_audit_logs_deleted
      + v_last_run.prior_retention_runs_deleted,
      0
    ),
    'telemetryRetentionDays', 30,
    'adminAuditRetentionMonths', 12,
    'requestAuditRetentionMonths', 12,
    'rawIpStored', false,
    'sessionReplayEnabled', false,
    'financeContentInTelemetry', false
  );
end;
$$;

revoke all on function private.get_privacy_governance_snapshot()
  from public, anon;
grant execute on function private.get_privacy_governance_snapshot()
  to authenticated;

comment on function public.apply_privacy_request_workflow(
  text, text, text, date, boolean
) is
  'Owner/admin structured privacy workflow transition. Accepts no request message, finance content, end-user identity, raw IP address, or payment credential.';

commit;
