begin;

alter table billing.plans
  add column if not exists currency_exponent smallint not null default 2;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'billing_plans_currency_exponent_check'
      and conrelid = 'billing.plans'::regclass
  ) then
    alter table billing.plans
      add constraint billing_plans_currency_exponent_check
      check (currency_exponent between 0 and 3);
  end if;
end;
$$;

comment on column billing.plans.currency_exponent is
  'Number of decimal places used to convert the displayed plan price into provider-neutral minor units.';

create table if not exists private.billing_plan_audit (
  id bigint generated by default as identity primary key,
  actor_admin_user_id uuid references auth.users(id) on delete set null,
  plan_code text not null,
  action text not null,
  before_name text,
  after_name text not null,
  before_billing_interval text,
  after_billing_interval text not null,
  before_price_minor bigint,
  after_price_minor bigint not null,
  before_currency text,
  after_currency text not null,
  before_currency_exponent smallint,
  after_currency_exponent smallint not null,
  before_is_active boolean,
  after_is_active boolean not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 months'),
  constraint billing_plan_audit_code_check check (
    plan_code ~ '^[a-z0-9][a-z0-9_-]{1,39}$'
  ),
  constraint billing_plan_audit_action_check check (
    action in ('created', 'updated', 'activated', 'deactivated')
  ),
  constraint billing_plan_audit_name_check check (
    char_length(after_name) between 1 and 80
    and (before_name is null or char_length(before_name) between 1 and 80)
  ),
  constraint billing_plan_audit_interval_check check (
    after_billing_interval in ('month', 'year', 'one_time')
    and (
      before_billing_interval is null
      or before_billing_interval in ('month', 'year', 'one_time')
    )
  ),
  constraint billing_plan_audit_price_check check (
    after_price_minor > 0
    and (before_price_minor is null or before_price_minor > 0)
  ),
  constraint billing_plan_audit_currency_check check (
    after_currency ~ '^[A-Z]{3}$'
    and (before_currency is null or before_currency ~ '^[A-Z]{3}$')
  ),
  constraint billing_plan_audit_exponent_check check (
    after_currency_exponent between 0 and 3
    and (
      before_currency_exponent is null
      or before_currency_exponent between 0 and 3
    )
  ),
  constraint billing_plan_audit_expiry_check check (expires_at >= created_at)
);

comment on table private.billing_plan_audit is
  'Owner-only plan-catalog audit. Stores commercial plan metadata only; never subscriber identity, card data, payment credentials, finance records, or raw webhook payloads.';

alter table private.billing_plan_audit enable row level security;

revoke all on private.billing_plan_audit from public, anon, authenticated;
revoke all on sequence private.billing_plan_audit_id_seq
  from public, anon, authenticated;

drop policy if exists billing_plan_audit_deny_direct
  on private.billing_plan_audit;
create policy billing_plan_audit_deny_direct
  on private.billing_plan_audit
  for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete on private.billing_plan_audit
  to service_role;
grant usage, select on sequence private.billing_plan_audit_id_seq
  to service_role;

create index if not exists billing_plan_audit_plan_created_idx
  on private.billing_plan_audit (plan_code, created_at desc);
create index if not exists billing_plan_audit_actor_created_idx
  on private.billing_plan_audit (actor_admin_user_id, created_at desc)
  where actor_admin_user_id is not null;
create index if not exists billing_plan_audit_expires_at_idx
  on private.billing_plan_audit (expires_at);

create or replace function private.apply_billing_plan_operation_impl(
  p_code text,
  p_name text,
  p_billing_interval text,
  p_price_major numeric,
  p_currency text,
  p_currency_exponent smallint default 2,
  p_is_active boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private, billing
as $$
declare
  v_admin_user_id uuid := auth.uid();
  v_admin_role text;
  v_code text := lower(btrim(p_code));
  v_name text := btrim(p_name);
  v_interval text := lower(btrim(p_billing_interval));
  v_currency text := upper(btrim(p_currency));
  v_exponent smallint := coalesce(p_currency_exponent, 2);
  v_price_minor bigint;
  v_before billing.plans%rowtype;
  v_after billing.plans%rowtype;
  v_action text;
begin
  select role
  into v_admin_role
  from private.platform_admins
  where user_id = v_admin_user_id
    and disabled_at is null;

  if v_admin_user_id is null or v_admin_role <> 'owner' then
    raise exception 'billing_owner_access_required' using errcode = '42501';
  end if;

  if v_code is null
     or v_code !~ '^[a-z0-9][a-z0-9_-]{1,39}$'
     or v_code = 'free' then
    raise exception 'billing_plan_code_invalid' using errcode = '22023';
  end if;

  if v_name is null
     or char_length(v_name) < 1
     or char_length(v_name) > 80
     or v_name ~ '[[:cntrl:]]' then
    raise exception 'billing_plan_name_invalid' using errcode = '22023';
  end if;

  if v_interval not in ('month', 'year', 'one_time') then
    raise exception 'billing_plan_interval_invalid' using errcode = '22023';
  end if;

  if v_currency is null or v_currency !~ '^[A-Z]{3}$' then
    raise exception 'billing_plan_currency_invalid' using errcode = '22023';
  end if;

  if v_exponent not between 0 and 3 then
    raise exception 'billing_plan_currency_exponent_invalid' using errcode = '22023';
  end if;

  if p_price_major is null
     or p_price_major <= 0
     or p_price_major > 1000000000 then
    raise exception 'billing_plan_price_invalid' using errcode = '22023';
  end if;

  if p_is_active is null then
    raise exception 'billing_plan_active_state_invalid' using errcode = '22023';
  end if;

  v_price_minor := round(
    p_price_major * power(10::numeric, v_exponent)
  )::bigint;

  if v_price_minor <= 0 then
    raise exception 'billing_plan_price_invalid' using errcode = '22023';
  end if;

  select *
  into v_before
  from billing.plans
  where code = v_code
  for update;

  if found and v_before.plan_kind <> 'paid' then
    raise exception 'billing_plan_kind_locked' using errcode = '22023';
  end if;

  if not found then
    insert into billing.plans (
      code,
      name,
      plan_kind,
      billing_interval,
      price_minor,
      currency,
      currency_exponent,
      is_active,
      updated_at
    )
    values (
      v_code,
      v_name,
      'paid',
      v_interval,
      v_price_minor,
      v_currency,
      v_exponent,
      p_is_active,
      now()
    )
    returning * into v_after;

    v_action := 'created';
  else
    update billing.plans
    set name = v_name,
        billing_interval = v_interval,
        price_minor = v_price_minor,
        currency = v_currency,
        currency_exponent = v_exponent,
        is_active = p_is_active,
        updated_at = now()
    where code = v_code
    returning * into v_after;

    v_action := case
      when v_before.is_active = false and v_after.is_active = true then 'activated'
      when v_before.is_active = true and v_after.is_active = false then 'deactivated'
      else 'updated'
    end;
  end if;

  insert into private.billing_plan_audit (
    actor_admin_user_id,
    plan_code,
    action,
    before_name,
    after_name,
    before_billing_interval,
    after_billing_interval,
    before_price_minor,
    after_price_minor,
    before_currency,
    after_currency,
    before_currency_exponent,
    after_currency_exponent,
    before_is_active,
    after_is_active
  )
  values (
    v_admin_user_id,
    v_after.code,
    v_action,
    case when v_before.code is null then null else v_before.name end,
    v_after.name,
    case when v_before.code is null then null else v_before.billing_interval end,
    v_after.billing_interval,
    case when v_before.code is null then null else v_before.price_minor end,
    v_after.price_minor,
    case when v_before.code is null then null else v_before.currency end,
    v_after.currency,
    case when v_before.code is null then null else v_before.currency_exponent end,
    v_after.currency_exponent,
    case when v_before.code is null then null else v_before.is_active end,
    v_after.is_active
  );

  return jsonb_build_object(
    'code', v_after.code,
    'name', v_after.name,
    'kind', v_after.plan_kind,
    'billingInterval', v_after.billing_interval,
    'priceMajor', round(
      v_after.price_minor::numeric
      / power(10::numeric, v_after.currency_exponent),
      v_after.currency_exponent
    ),
    'currency', v_after.currency,
    'currencyExponent', v_after.currency_exponent,
    'isActive', v_after.is_active,
    'action', v_action,
    'featurePolicy', 'unlimited'
  );
end;
$$;

revoke all on function private.apply_billing_plan_operation_impl(
  text, text, text, numeric, text, smallint, boolean
) from public, anon;
grant execute on function private.apply_billing_plan_operation_impl(
  text, text, text, numeric, text, smallint, boolean
) to authenticated;

create or replace function public.apply_billing_plan_operation(
  p_code text,
  p_name text,
  p_billing_interval text,
  p_price_major numeric,
  p_currency text,
  p_currency_exponent smallint default 2,
  p_is_active boolean default true
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.apply_billing_plan_operation_impl(
    p_code,
    p_name,
    p_billing_interval,
    p_price_major,
    p_currency,
    p_currency_exponent,
    p_is_active
  );
$$;

revoke all on function public.apply_billing_plan_operation(
  text, text, text, numeric, text, smallint, boolean
) from public, anon;
grant execute on function public.apply_billing_plan_operation(
  text, text, text, numeric, text, smallint, boolean
) to authenticated;

comment on function public.apply_billing_plan_operation(
  text, text, text, numeric, text, smallint, boolean
) is
  'Owner-only provider-neutral plan catalog mutation. Does not configure checkout, store payment credentials, attach feature limits, or alter subscriber finance records.';

create or replace function private.get_billing_operations_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private, billing
as $$
declare
  v_admin_user_id uuid := auth.uid();
  v_admin_role text;
begin
  select role
  into v_admin_role
  from private.platform_admins
  where user_id = v_admin_user_id
    and disabled_at is null;

  if v_admin_user_id is null or v_admin_role is null then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'operationsAllowed', v_admin_role = 'owner',
    'providerConnected', exists (
      select 1
      from billing.customers
      where provider <> 'none'
        and provider_customer_id is not null
    ),
    'planCatalog', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'code', plans.code,
          'name', plans.name,
          'kind', plans.plan_kind,
          'billingInterval', plans.billing_interval,
          'priceMajor', plans.price_major,
          'currency', plans.currency,
          'currencyExponent', plans.currency_exponent,
          'isActive', plans.is_active,
          'totalUsers', plans.total_users,
          'trialUsers', plans.trial_users,
          'activeUsers', plans.active_users,
          'pastDueUsers', plans.past_due_users,
          'cancelledUsers', plans.cancelled_users,
          'editable', v_admin_role = 'owner' and plans.code <> 'free'
        )
        order by plans.is_active desc, plans.plan_kind, plans.code
      )
      from (
        select
          p.code,
          p.name,
          p.plan_kind,
          p.billing_interval,
          case
            when p.price_minor is null then null
            else round(
              p.price_minor::numeric / power(10::numeric, p.currency_exponent),
              p.currency_exponent
            )
          end as price_major,
          p.currency,
          p.currency_exponent,
          p.is_active,
          count(s.id)::bigint as total_users,
          count(s.id) filter (where s.status = 'trialing')::bigint as trial_users,
          count(s.id) filter (where s.status = 'active')::bigint as active_users,
          count(s.id) filter (where s.status = 'past_due')::bigint as past_due_users,
          count(s.id) filter (
            where s.status in ('cancelled', 'expired')
          )::bigint as cancelled_users
        from billing.plans p
        left join billing.subscriptions s on s.plan_code = p.code
        group by
          p.code,
          p.name,
          p.plan_kind,
          p.billing_interval,
          p.price_minor,
          p.currency,
          p.currency_exponent,
          p.is_active
        limit 40
      ) as plans
    ), '[]'::jsonb),
    'webhooks', jsonb_build_object(
      'received24h', (
        select count(*)::bigint
        from billing.webhook_events
        where received_at >= now() - interval '24 hours'
      ),
      'pending', (
        select count(*)::bigint
        from billing.webhook_events
        where processing_status = 'received'
      ),
      'processed24h', (
        select count(*)::bigint
        from billing.webhook_events
        where processing_status = 'processed'
          and processed_at >= now() - interval '24 hours'
      ),
      'failed24h', (
        select count(*)::bigint
        from billing.webhook_events
        where processing_status = 'failed'
          and received_at >= now() - interval '24 hours'
      ),
      'ignored24h', (
        select count(*)::bigint
        from billing.webhook_events
        where processing_status = 'ignored'
          and received_at >= now() - interval '24 hours'
      ),
      'lastReceivedAt', (
        select max(received_at) from billing.webhook_events
      ),
      'lastProcessedAt', (
        select max(processed_at) from billing.webhook_events
      ),
      'expiredPending', (
        select count(*)::bigint
        from billing.webhook_events
        where expires_at <= now()
      )
    ),
    'auditEvents30d', (
      select count(*)::bigint
      from private.billing_plan_audit
      where created_at >= now() - interval '30 days'
    ),
    'expiredAuditPending', (
      select count(*)::bigint
      from private.billing_plan_audit
      where expires_at <= now()
    ),
    'rawWebhookPayloadStored', false,
    'cardDataStored', false,
    'featureLimitsAttached', false
  );
end;
$$;

revoke all on function private.get_billing_operations_snapshot()
  from public, anon;
grant execute on function private.get_billing_operations_snapshot()
  to authenticated;

create or replace function private.get_platform_admin_snapshot()
returns jsonb
language sql
security definer
set search_path = pg_catalog, private
as $$
  select private.get_platform_admin_snapshot_base()
    || jsonb_build_object(
      'privacy', private.get_privacy_governance_snapshot()
    )
    || jsonb_build_object(
      'billingOperations', private.get_billing_operations_snapshot()
    );
$$;

revoke all on function private.get_platform_admin_snapshot()
  from public, anon;
grant execute on function private.get_platform_admin_snapshot()
  to authenticated;

create or replace function private.purge_expired_billing_operational_data()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, private, billing
as $$
declare
  v_webhook_events_deleted bigint := 0;
  v_plan_audit_deleted bigint := 0;
begin
  delete from billing.webhook_events
  where expires_at <= now();
  get diagnostics v_webhook_events_deleted = row_count;

  delete from private.billing_plan_audit
  where expires_at <= now();
  get diagnostics v_plan_audit_deleted = row_count;

  return jsonb_build_object(
    'webhookEventsDeleted', v_webhook_events_deleted,
    'planAuditEventsDeleted', v_plan_audit_deleted,
    'ranAt', now()
  );
end;
$$;

revoke all on function private.purge_expired_billing_operational_data()
  from public, anon, authenticated;
grant execute on function private.purge_expired_billing_operational_data()
  to service_role;

commit;
