begin;

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated, service_role;

create schema if not exists billing;
revoke all on schema billing from public, anon, authenticated;
grant usage on schema billing to service_role;

create table if not exists private.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'owner',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  disabled_at timestamptz,
  constraint platform_admins_role_check check (
    role in ('owner', 'admin', 'analyst', 'support')
  )
);

comment on table private.platform_admins is
  'Private platform-level administration grants. Never expose through the Data API or client application.';

create table if not exists private.admin_access_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  route text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 months'),
  constraint admin_access_log_action_check check (
    action in ('control_center_viewed', 'billing_snapshot_viewed')
  ),
  constraint admin_access_log_route_check check (
    char_length(route) between 1 and 120
    and route like '/%'
    and route !~ '[?#[:cntrl:]]'
  )
);

comment on table private.admin_access_log is
  'Audits access to private aggregate administration views. Contains no end-user finance content.';

create table if not exists billing.plans (
  code text primary key,
  name text not null,
  plan_kind text not null,
  billing_interval text not null,
  price_minor bigint,
  currency text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_plans_code_check check (
    code ~ '^[a-z0-9][a-z0-9_-]{1,39}$'
  ),
  constraint billing_plans_name_check check (
    char_length(name) between 1 and 80
  ),
  constraint billing_plans_kind_check check (
    plan_kind in ('free', 'paid')
  ),
  constraint billing_plans_interval_check check (
    billing_interval in ('free', 'month', 'year', 'one_time')
  ),
  constraint billing_plans_price_check check (
    price_minor is null or price_minor >= 0
  ),
  constraint billing_plans_currency_check check (
    currency is null or currency ~ '^[A-Z]{3}$'
  ),
  constraint billing_plans_paid_price_check check (
    (
      plan_kind = 'free'
      and billing_interval = 'free'
      and coalesce(price_minor, 0) = 0
    )
    or (
      plan_kind = 'paid'
      and billing_interval in ('month', 'year', 'one_time')
    )
  )
);

comment on table billing.plans is
  'Provider-neutral billing segmentation. Plans do not contain product feature limits.';

create table if not exists billing.customers (
  user_id uuid primary key references auth.users(id) on delete cascade,
  provider text not null,
  provider_customer_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_customers_provider_check check (
    provider in ('none', 'stripe', 'paddle', 'manual')
  ),
  constraint billing_customers_reference_check check (
    provider_customer_id is null
    or char_length(provider_customer_id) between 1 and 160
  ),
  constraint billing_customers_provider_reference_check check (
    (provider = 'none' and provider_customer_id is null)
    or provider <> 'none'
  )
);

comment on table billing.customers is
  'Server-only mapping to a payment provider customer reference. No card or bank credentials are stored.';

create unique index if not exists billing_customers_provider_reference_key
  on billing.customers (provider, provider_customer_id)
  where provider_customer_id is not null;

create table if not exists billing.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  plan_code text not null references billing.plans(code) on update cascade,
  status text not null default 'free',
  provider text not null default 'none',
  provider_subscription_id text,
  trial_ends_at timestamptz,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_subscriptions_status_check check (
    status in (
      'free',
      'trialing',
      'active',
      'past_due',
      'paused',
      'cancelled',
      'expired',
      'incomplete'
    )
  ),
  constraint billing_subscriptions_provider_check check (
    provider in ('none', 'stripe', 'paddle', 'manual')
  ),
  constraint billing_subscriptions_reference_check check (
    provider_subscription_id is null
    or char_length(provider_subscription_id) between 1 and 180
  ),
  constraint billing_subscriptions_provider_reference_check check (
    (provider = 'none' and provider_subscription_id is null)
    or provider <> 'none'
  ),
  constraint billing_subscriptions_period_check check (
    current_period_end is null
    or current_period_start is null
    or current_period_end >= current_period_start
  )
);

comment on table billing.subscriptions is
  'Current provider-neutral subscription state for aggregate reporting and future webhook synchronization.';

create unique index if not exists billing_subscriptions_provider_reference_key
  on billing.subscriptions (provider, provider_subscription_id)
  where provider_subscription_id is not null;

create index if not exists billing_subscriptions_status_plan_idx
  on billing.subscriptions (status, plan_code);

create index if not exists billing_subscriptions_period_end_idx
  on billing.subscriptions (current_period_end)
  where current_period_end is not null;

create table if not exists billing.webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  processing_status text not null default 'received',
  payload_sha256 text not null,
  error_code text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '90 days'),
  constraint billing_webhook_provider_check check (
    provider in ('stripe', 'paddle', 'manual')
  ),
  constraint billing_webhook_event_id_check check (
    char_length(provider_event_id) between 1 and 180
  ),
  constraint billing_webhook_event_type_check check (
    char_length(event_type) between 1 and 120
    and event_type !~ '[[:cntrl:]]'
  ),
  constraint billing_webhook_status_check check (
    processing_status in ('received', 'processed', 'ignored', 'failed')
  ),
  constraint billing_webhook_payload_hash_check check (
    payload_sha256 ~ '^[a-f0-9]{64}$'
  ),
  constraint billing_webhook_error_code_check check (
    error_code is null or error_code ~ '^[A-Z0-9_]{1,80}$'
  )
);

comment on table billing.webhook_events is
  'Idempotency and processing audit for future payment webhooks. Stores a payload hash, never the raw provider payload.';

create unique index if not exists billing_webhook_provider_event_key
  on billing.webhook_events (provider, provider_event_id);

create index if not exists billing_webhook_expires_at_idx
  on billing.webhook_events (expires_at);

alter table private.platform_admins enable row level security;
alter table private.admin_access_log enable row level security;
alter table billing.plans enable row level security;
alter table billing.customers enable row level security;
alter table billing.subscriptions enable row level security;
alter table billing.webhook_events enable row level security;

revoke all on private.platform_admins, private.admin_access_log
  from public, anon, authenticated;
revoke all on billing.plans, billing.customers, billing.subscriptions, billing.webhook_events
  from public, anon, authenticated;
revoke all on sequence private.admin_access_log_id_seq, billing.webhook_events_id_seq
  from public, anon, authenticated;

drop policy if exists platform_admins_deny_direct on private.platform_admins;
create policy platform_admins_deny_direct
  on private.platform_admins
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists admin_access_log_deny_direct on private.admin_access_log;
create policy admin_access_log_deny_direct
  on private.admin_access_log
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists billing_plans_deny_direct on billing.plans;
create policy billing_plans_deny_direct
  on billing.plans
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists billing_customers_deny_direct on billing.customers;
create policy billing_customers_deny_direct
  on billing.customers
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists billing_subscriptions_deny_direct on billing.subscriptions;
create policy billing_subscriptions_deny_direct
  on billing.subscriptions
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists billing_webhook_events_deny_direct on billing.webhook_events;
create policy billing_webhook_events_deny_direct
  on billing.webhook_events
  for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete
  on private.platform_admins, private.admin_access_log
  to service_role;
grant usage, select on sequence private.admin_access_log_id_seq to service_role;

grant select, insert, update, delete
  on billing.plans, billing.customers, billing.subscriptions, billing.webhook_events
  to service_role;
grant usage, select on sequence billing.webhook_events_id_seq to service_role;

insert into billing.plans (
  code,
  name,
  plan_kind,
  billing_interval,
  price_minor,
  currency
)
values ('free', 'Free', 'free', 'free', 0, null)
on conflict (code) do update
set name = excluded.name,
    plan_kind = excluded.plan_kind,
    billing_interval = excluded.billing_interval,
    price_minor = excluded.price_minor,
    currency = excluded.currency,
    is_active = true,
    updated_at = now();

insert into billing.subscriptions (user_id, plan_code, status, provider)
select id, 'free', 'free', 'none'
from auth.users
where deleted_at is null
  and coalesce(is_anonymous, false) = false
on conflict (user_id) do nothing;

create or replace function private.create_default_billing_subscription()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, billing
as $$
begin
  if coalesce(new.is_anonymous, false) = false then
    insert into billing.subscriptions (user_id, plan_code, status, provider)
    values (new.id, 'free', 'free', 'none')
    on conflict (user_id) do nothing;
  end if;

  return new;
exception
  when others then
    -- Billing initialization must never block account creation.
    return new;
end;
$$;

revoke all on function private.create_default_billing_subscription()
  from public, anon, authenticated;

drop trigger if exists create_default_billing_subscription on auth.users;
create trigger create_default_billing_subscription
after insert on auth.users
for each row execute function private.create_default_billing_subscription();

create or replace function private.get_my_billing_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, billing
as $$
declare
  v_user_id uuid := auth.uid();
  v_snapshot jsonb;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'planCode', p.code,
    'planName', p.name,
    'planKind', p.plan_kind,
    'billingInterval', p.billing_interval,
    'status', s.status,
    'trialEndsAt', s.trial_ends_at,
    'currentPeriodEnd', s.current_period_end,
    'cancelAtPeriodEnd', s.cancel_at_period_end,
    'featurePolicy', 'unlimited'
  )
  into v_snapshot
  from billing.subscriptions s
  join billing.plans p on p.code = s.plan_code
  where s.user_id = v_user_id;

  return coalesce(
    v_snapshot,
    jsonb_build_object(
      'planCode', 'free',
      'planName', 'Free',
      'planKind', 'free',
      'billingInterval', 'free',
      'status', 'free',
      'trialEndsAt', null,
      'currentPeriodEnd', null,
      'cancelAtPeriodEnd', false,
      'featurePolicy', 'unlimited'
    )
  );
end;
$$;

create or replace function public.get_my_billing_snapshot()
returns jsonb
language sql
stable
security invoker
set search_path = pg_catalog, private
as $$
  select private.get_my_billing_snapshot();
$$;

revoke all on function private.get_my_billing_snapshot() from public, anon;
grant execute on function private.get_my_billing_snapshot() to authenticated;
revoke all on function public.get_my_billing_snapshot() from public, anon;
grant execute on function public.get_my_billing_snapshot() to authenticated;

create or replace function private.get_platform_admin_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private, billing, telemetry
as $$
declare
  v_admin_user_id uuid := auth.uid();
  v_admin_role text;
  v_plan_breakdown jsonb := '[]'::jsonb;
  v_device_breakdown jsonb := '[]'::jsonb;
  v_country_breakdown jsonb := '[]'::jsonb;
  v_top_routes jsonb := '[]'::jsonb;
  v_slow_routes jsonb := '[]'::jsonb;
begin
  select role
  into v_admin_role
  from private.platform_admins
  where user_id = v_admin_user_id
    and disabled_at is null;

  if v_admin_user_id is null or v_admin_role is null then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  insert into private.admin_access_log (admin_user_id, action, route)
  values (v_admin_user_id, 'control_center_viewed', '/admin');

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'code', code,
        'name', name,
        'kind', plan_kind,
        'status', status,
        'users', users
      )
      order by users desc, code
    ),
    '[]'::jsonb
  )
  into v_plan_breakdown
  from (
    select
      p.code,
      p.name,
      p.plan_kind,
      s.status,
      count(*)::bigint as users
    from billing.subscriptions s
    join billing.plans p on p.code = s.plan_code
    group by p.code, p.name, p.plan_kind, s.status
  ) plan_rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object('device', device_type, 'users', users)
      order by users desc
    ),
    '[]'::jsonb
  )
  into v_device_breakdown
  from (
    select device_type, count(distinct subject_id)::bigint as users
    from telemetry.events
    where occurred_at >= now() - interval '30 days'
    group by device_type
    order by users desc
    limit 6
  ) device_rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object('country', country_code, 'users', users)
      order by users desc
    ),
    '[]'::jsonb
  )
  into v_country_breakdown
  from (
    select country_code, count(distinct subject_id)::bigint as users
    from telemetry.events
    where occurred_at >= now() - interval '30 days'
      and country_code is not null
    group by country_code
    order by users desc
    limit 8
  ) country_rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object('route', route, 'events', events)
      order by events desc
    ),
    '[]'::jsonb
  )
  into v_top_routes
  from (
    select route, count(*)::bigint as events
    from telemetry.events
    where occurred_at >= now() - interval '7 days'
    group by route
    order by events desc
    limit 8
  ) route_rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object('route', route, 'signals', signals)
      order by signals desc
    ),
    '[]'::jsonb
  )
  into v_slow_routes
  from (
    select route, count(*)::bigint as signals
    from telemetry.events
    where occurred_at >= now() - interval '7 days'
      and (
        (event_name = 'web_vital' and metric_rating = 'poor')
        or event_name = 'long_task'
      )
    group by route
    order by signals desc
    limit 8
  ) slow_rows;

  return jsonb_build_object(
    'generatedAt', now(),
    'adminRole', v_admin_role,
    'featurePolicy', 'unlimited',
    'users', jsonb_build_object(
      'total', (
        select count(*)::bigint
        from auth.users
        where deleted_at is null
          and coalesce(is_anonymous, false) = false
      ),
      'new7d', (
        select count(*)::bigint
        from auth.users
        where deleted_at is null
          and coalesce(is_anonymous, false) = false
          and created_at >= now() - interval '7 days'
      ),
      'new30d', (
        select count(*)::bigint
        from auth.users
        where deleted_at is null
          and coalesce(is_anonymous, false) = false
          and created_at >= now() - interval '30 days'
      ),
      'signedIn24h', (
        select count(*)::bigint
        from auth.users
        where deleted_at is null
          and coalesce(is_anonymous, false) = false
          and last_sign_in_at >= now() - interval '24 hours'
      ),
      'signedIn30d', (
        select count(*)::bigint
        from auth.users
        where deleted_at is null
          and coalesce(is_anonymous, false) = false
          and last_sign_in_at >= now() - interval '30 days'
      )
    ),
    'billing', jsonb_build_object(
      'freeUsers', (
        select count(*)::bigint
        from billing.subscriptions
        where status = 'free'
      ),
      'trialUsers', (
        select count(*)::bigint
        from billing.subscriptions
        where status = 'trialing'
      ),
      'paidUsers', (
        select count(*)::bigint
        from billing.subscriptions s
        join billing.plans p on p.code = s.plan_code
        where p.plan_kind = 'paid'
          and s.status = 'active'
      ),
      'pastDueUsers', (
        select count(*)::bigint
        from billing.subscriptions
        where status = 'past_due'
      ),
      'cancelledUsers', (
        select count(*)::bigint
        from billing.subscriptions
        where status in ('cancelled', 'expired')
      ),
      'providerConnected', exists (
        select 1
        from billing.customers
        where provider <> 'none'
          and provider_customer_id is not null
      ),
      'plans', v_plan_breakdown
    ),
    'telemetry', jsonb_build_object(
      'activeUsers24h', (
        select count(distinct subject_id)::bigint
        from telemetry.events
        where occurred_at >= now() - interval '24 hours'
      ),
      'activeUsers30d', (
        select count(distinct subject_id)::bigint
        from telemetry.events
        where occurred_at >= now() - interval '30 days'
      ),
      'events24h', (
        select count(*)::bigint
        from telemetry.events
        where occurred_at >= now() - interval '24 hours'
      ),
      'failedOperations7d', (
        select count(*)::bigint
        from telemetry.events
        where occurred_at >= now() - interval '7 days'
          and event_name = 'operation_failed'
      ),
      'poorPerformanceSignals7d', (
        select count(*)::bigint
        from telemetry.events
        where occurred_at >= now() - interval '7 days'
          and (
            (event_name = 'web_vital' and metric_rating = 'poor')
            or event_name = 'long_task'
          )
      ),
      'devices', v_device_breakdown,
      'countries', v_country_breakdown,
      'topRoutes', v_top_routes,
      'slowRoutes', v_slow_routes
    )
  );
end;
$$;

create or replace function public.get_platform_admin_snapshot()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.get_platform_admin_snapshot();
$$;

revoke all on function private.get_platform_admin_snapshot()
  from public, anon;
grant execute on function private.get_platform_admin_snapshot()
  to authenticated;
revoke all on function public.get_platform_admin_snapshot()
  from public, anon;
grant execute on function public.get_platform_admin_snapshot()
  to authenticated;

create index if not exists admin_access_log_created_at_idx
  on private.admin_access_log (created_at desc);

create index if not exists admin_access_log_expires_at_idx
  on private.admin_access_log (expires_at);

commit;
