begin;

create table if not exists private.privacy_requests (
  id uuid primary key default gen_random_uuid(),
  request_code text not null unique default (
    'PRV-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))
  ),
  subject_user_id uuid references auth.users(id) on delete set null,
  request_type text not null,
  status text not null default 'pending',
  verification_status text not null default 'not_started',
  source text not null default 'manual',
  assigned_admin_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  due_at timestamptz,
  closed_at timestamptz,
  constraint privacy_requests_code_check check (
    request_code ~ '^PRV-[A-F0-9]{12}$'
  ),
  constraint privacy_requests_type_check check (
    request_type in (
      'access',
      'export',
      'correction',
      'deletion',
      'restriction',
      'objection',
      'consent_review',
      'security_review'
    )
  ),
  constraint privacy_requests_status_check check (
    status in (
      'pending',
      'identity_verification',
      'in_progress',
      'completed',
      'rejected',
      'cancelled'
    )
  ),
  constraint privacy_requests_verification_check check (
    verification_status in ('not_started', 'pending', 'verified', 'failed')
  ),
  constraint privacy_requests_source_check check (
    source in ('in_product', 'support', 'manual', 'system')
  ),
  constraint privacy_requests_due_check check (
    due_at is null or due_at >= created_at
  ),
  constraint privacy_requests_closed_check check (
    closed_at is null or closed_at >= created_at
  )
);

comment on table private.privacy_requests is
  'Server-only privacy request queue. Stores workflow state and references, never finance content, request-message bodies, passwords, raw IP addresses, or payment data.';

create table if not exists private.privacy_retention_runs (
  id bigint generated by default as identity primary key,
  initiated_by text not null default 'service_role',
  actor_admin_user_id uuid references auth.users(id) on delete set null,
  telemetry_events_deleted bigint not null default 0,
  admin_access_logs_deleted bigint not null default 0,
  prior_retention_runs_deleted bigint not null default 0,
  ran_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 months'),
  constraint privacy_retention_runs_initiator_check check (
    initiated_by in ('scheduled', 'service_role', 'manual')
  ),
  constraint privacy_retention_runs_counts_check check (
    telemetry_events_deleted >= 0
    and admin_access_logs_deleted >= 0
    and prior_retention_runs_deleted >= 0
  )
);

comment on table private.privacy_retention_runs is
  'Aggregate audit of retention cleanup. Contains deletion counts only and no end-user identity or finance content.';

alter table private.privacy_requests enable row level security;
alter table private.privacy_retention_runs enable row level security;

revoke all on private.privacy_requests, private.privacy_retention_runs
  from public, anon, authenticated;
revoke all on sequence private.privacy_retention_runs_id_seq
  from public, anon, authenticated;

drop policy if exists privacy_requests_deny_direct on private.privacy_requests;
create policy privacy_requests_deny_direct
  on private.privacy_requests
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists privacy_retention_runs_deny_direct
  on private.privacy_retention_runs;
create policy privacy_retention_runs_deny_direct
  on private.privacy_retention_runs
  for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete
  on private.privacy_requests, private.privacy_retention_runs
  to service_role;
grant usage, select on sequence private.privacy_retention_runs_id_seq
  to service_role;

create index if not exists privacy_requests_status_created_idx
  on private.privacy_requests (status, created_at desc);
create index if not exists privacy_requests_due_open_idx
  on private.privacy_requests (due_at)
  where due_at is not null
    and status in ('pending', 'identity_verification', 'in_progress');
create index if not exists privacy_requests_subject_idx
  on private.privacy_requests (subject_user_id)
  where subject_user_id is not null;
create index if not exists privacy_requests_assignee_idx
  on private.privacy_requests (assigned_admin_user_id)
  where assigned_admin_user_id is not null;
create index if not exists privacy_retention_runs_ran_at_idx
  on private.privacy_retention_runs (ran_at desc);
create index if not exists privacy_retention_runs_expires_at_idx
  on private.privacy_retention_runs (expires_at);

create or replace function private.purge_expired_privacy_operational_data(
  p_initiated_by text default 'service_role',
  p_actor_admin_user_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, private, telemetry
as $$
declare
  v_telemetry_deleted bigint := 0;
  v_admin_logs_deleted bigint := 0;
  v_old_runs_deleted bigint := 0;
begin
  if p_initiated_by not in ('scheduled', 'service_role', 'manual') then
    raise exception 'privacy_retention_initiator_invalid' using errcode = '22023';
  end if;

  delete from telemetry.events
  where expires_at <= now();
  get diagnostics v_telemetry_deleted = row_count;

  delete from private.admin_access_log
  where expires_at <= now();
  get diagnostics v_admin_logs_deleted = row_count;

  delete from private.privacy_retention_runs
  where expires_at <= now();
  get diagnostics v_old_runs_deleted = row_count;

  insert into private.privacy_retention_runs (
    initiated_by,
    actor_admin_user_id,
    telemetry_events_deleted,
    admin_access_logs_deleted,
    prior_retention_runs_deleted
  )
  values (
    p_initiated_by,
    p_actor_admin_user_id,
    v_telemetry_deleted,
    v_admin_logs_deleted,
    v_old_runs_deleted
  );

  return jsonb_build_object(
    'telemetryEventsDeleted', v_telemetry_deleted,
    'adminAccessLogsDeleted', v_admin_logs_deleted,
    'priorRetentionRunsDeleted', v_old_runs_deleted,
    'ranAt', now()
  );
end;
$$;

revoke all on function private.purge_expired_privacy_operational_data(text, uuid)
  from public, anon, authenticated;
grant execute on function private.purge_expired_privacy_operational_data(text, uuid)
  to service_role;

-- Preserve the existing user, billing and telemetry snapshot as an isolated base.
do $$
begin
  if to_regprocedure('private.get_platform_admin_snapshot_base()') is null
     and to_regprocedure('private.get_platform_admin_snapshot()') is not null then
    execute 'alter function private.get_platform_admin_snapshot() rename to get_platform_admin_snapshot_base';
  end if;
end;
$$;

create or replace function private.get_privacy_governance_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private, telemetry
as $$
declare
  v_admin_user_id uuid := auth.uid();
  v_admin_role text;
  v_last_run private.privacy_retention_runs%rowtype;
begin
  select role
  into v_admin_role
  from private.platform_admins
  where user_id = v_admin_user_id
    and disabled_at is null;

  if v_admin_user_id is null or v_admin_role is null then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  select *
  into v_last_run
  from private.privacy_retention_runs
  order by ran_at desc
  limit 1;

  return jsonb_build_object(
    'openRequests', (
      select count(*)::bigint
      from private.privacy_requests
      where status in ('pending', 'identity_verification', 'in_progress')
    ),
    'overdueRequests', (
      select count(*)::bigint
      from private.privacy_requests
      where status in ('pending', 'identity_verification', 'in_progress')
        and due_at is not null
        and due_at < now()
    ),
    'completedRequests30d', (
      select count(*)::bigint
      from private.privacy_requests
      where status = 'completed'
        and closed_at >= now() - interval '30 days'
    ),
    'adminViews30d', (
      select count(*)::bigint
      from private.admin_access_log
      where created_at >= now() - interval '30 days'
    ),
    'telemetryEventsStored', (
      select count(*)::bigint from telemetry.events
    ),
    'telemetrySubjectsStored', (
      select count(*)::bigint from telemetry.subjects
    ),
    'expiredTelemetryPending', (
      select count(*)::bigint
      from telemetry.events
      where expires_at <= now()
    ),
    'expiredAdminAuditPending', (
      select count(*)::bigint
      from private.admin_access_log
      where expires_at <= now()
    ),
    'lastRetentionRunAt', v_last_run.ran_at,
    'lastRetentionRowsDeleted', coalesce(
      v_last_run.telemetry_events_deleted
      + v_last_run.admin_access_logs_deleted
      + v_last_run.prior_retention_runs_deleted,
      0
    ),
    'telemetryRetentionDays', 30,
    'adminAuditRetentionMonths', 12,
    'rawIpStored', false,
    'sessionReplayEnabled', false,
    'financeContentInTelemetry', false
  );
end;
$$;

revoke all on function private.get_privacy_governance_snapshot()
  from public, anon;
grant execute on function private.get_privacy_governance_snapshot()
  to authenticated;

create or replace function private.get_platform_admin_snapshot()
returns jsonb
language sql
security definer
set search_path = pg_catalog, private
as $$
  select private.get_platform_admin_snapshot_base()
    || jsonb_build_object(
      'privacy', private.get_privacy_governance_snapshot()
    );
$$;

revoke all on function private.get_platform_admin_snapshot()
  from public, anon;
grant execute on function private.get_platform_admin_snapshot()
  to authenticated;

create or replace function public.get_platform_admin_snapshot()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.get_platform_admin_snapshot();
$$;

revoke all on function public.get_platform_admin_snapshot()
  from public, anon;
grant execute on function public.get_platform_admin_snapshot()
  to authenticated;

comment on function public.get_platform_admin_snapshot() is
  'Owner/admin aggregate control-center snapshot. Exposes no user list, finance content, raw IP address, payment credential, or privacy-request message body.';

commit;
