create or replace function private.get_business_fx_snapshot_internal(p_business_id uuid,p_limit integer default 200)
returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,private
as $$
declare actor uuid:=auth.uid();v_base text;v_limit integer:=least(greatest(coalesce(p_limit,200),10),500);v_settings jsonb;v_rates jsonb;v_runs jsonb;v_lines jsonb;v_receivables jsonb;v_payables jsonb;v_banks jsonb;v_settlements jsonb;v_audit jsonb;v_summary jsonb;v_currencies jsonb;
begin
  if actor is null or not private.can_view_business_fx(p_business_id) then raise exception 'FX workspace access required.' using errcode='42501';end if;
  select base_currency into v_base from public.businesses where id=p_business_id and status='active';
  if v_base is null then raise exception 'Active business not found.' using errcode='P0002';end if;
  select jsonb_build_object('realized_gain_account',jsonb_build_object('id',rg.id,'code',rg.code,'name',rg.name),'realized_loss_account',jsonb_build_object('id',rl.id,'code',rl.code,'name',rl.name),'unrealized_gain_account',jsonb_build_object('id',ug.id,'code',ug.code,'name',ug.name),'unrealized_loss_account',jsonb_build_object('id',ul.id,'code',ul.code,'name',ul.name)) into v_settings
  from public.business_fx_settings settings join public.business_chart_of_accounts rg on rg.business_id=settings.business_id and rg.id=settings.realized_gain_account_id join public.business_chart_of_accounts rl on rl.business_id=settings.business_id and rl.id=settings.realized_loss_account_id join public.business_chart_of_accounts ug on ug.business_id=settings.business_id and ug.id=settings.unrealized_gain_account_id join public.business_chart_of_accounts ul on ul.business_id=settings.business_id and ul.id=settings.unrealized_loss_account_id where settings.business_id=p_business_id;
  select coalesce(jsonb_agg(jsonb_build_object('id',rate.id,'currency',rate.currency,'rate_date',rate.rate_date,'rate_to_base',rate.rate_to_base,'source',rate.source,'notes',rate.notes,'created_at',rate.created_at) order by rate.rate_date desc,rate.currency),'[]'::jsonb) into v_rates from (select * from public.business_fx_rates where business_id=p_business_id order by rate_date desc,currency limit v_limit) rate;
  select coalesce(jsonb_agg(jsonb_build_object('id',run.id,'run_number',run.run_number,'run_code',run.run_code,'closing_date',run.closing_date,'status',run.status,'exposure_count',run.exposure_count,'skipped_bank_count',run.skipped_bank_count,'total_gain_base',run.total_gain_base,'total_loss_base',run.total_loss_base,'journal_entry_id',run.journal_entry_id,'reversal_journal_entry_id',run.reversal_journal_entry_id,'reversal_date',run.reversal_date,'notes',run.notes,'created_at',run.created_at,'posted_at',run.posted_at,'reversed_at',run.reversed_at) order by run.closing_date desc,run.run_number desc),'[]'::jsonb) into v_runs from (select * from public.business_fx_revaluation_runs where business_id=p_business_id order by closing_date desc,run_number desc limit 100) run;
  select coalesce(jsonb_agg(jsonb_build_object('id',line.id,'revaluation_run_id',line.revaluation_run_id,'exposure_type',line.exposure_type,'exposure_id',line.exposure_id,'exposure_code',line.exposure_code,'account_id',line.account_id,'currency',line.currency,'transaction_balance',line.transaction_balance,'carrying_base',line.carrying_base,'rate_id',line.rate_id,'closing_rate',line.closing_rate,'revalued_base',line.revalued_base,'adjustment_base',line.adjustment_base) order by run.closing_date desc,line.exposure_type,line.exposure_code),'[]'::jsonb) into v_lines from public.business_fx_revaluation_lines line join public.business_fx_revaluation_runs run on run.business_id=line.business_id and run.id=line.revaluation_run_id where line.business_id=p_business_id and run.id in(select id from public.business_fx_revaluation_runs where business_id=p_business_id order by closing_date desc limit 20);
  select coalesce(jsonb_agg(jsonb_build_object('id',invoice.id,'code',invoice.invoice_code,'date',invoice.invoice_date,'due_date',invoice.due_date,'currency',invoice.currency,'transaction_balance',invoice.total_transaction-invoice.paid_transaction-invoice.returned_transaction,'carrying_base',invoice.total_base-invoice.paid_base-invoice.returned_base,'latest_rate_date',rate.rate_date,'latest_rate',rate.rate_to_base,'estimated_base',case when rate.rate_to_base is null then null else round((invoice.total_transaction-invoice.paid_transaction-invoice.returned_transaction)*rate.rate_to_base,2) end) order by invoice.due_date,invoice.invoice_code),'[]'::jsonb) into v_receivables
  from public.business_sales_invoices invoice left join lateral (select fx.rate_date,fx.rate_to_base from public.business_fx_rates fx where fx.business_id=p_business_id and fx.currency=invoice.currency order by fx.rate_date desc limit 1) rate on true where invoice.business_id=p_business_id and invoice.status in('issued','partially_paid') and invoice.currency<>v_base and invoice.total_transaction-invoice.paid_transaction-invoice.returned_transaction>0;
  select coalesce(jsonb_agg(jsonb_build_object('id',bill.id,'code',bill.bill_code,'date',bill.bill_date,'due_date',bill.due_date,'currency',bill.currency,'transaction_balance',bill.total_transaction-bill.paid_transaction-bill.returned_transaction,'carrying_base',bill.total_base-bill.paid_base-bill.returned_base,'latest_rate_date',rate.rate_date,'latest_rate',rate.rate_to_base,'estimated_base',case when rate.rate_to_base is null then null else round((bill.total_transaction-bill.paid_transaction-bill.returned_transaction)*rate.rate_to_base,2) end) order by bill.due_date,bill.bill_code),'[]'::jsonb) into v_payables
  from public.business_supplier_bills bill left join lateral (select fx.rate_date,fx.rate_to_base from public.business_fx_rates fx where fx.business_id=p_business_id and fx.currency=bill.currency order by fx.rate_date desc limit 1) rate on true where bill.business_id=p_business_id and bill.status in('issued','partially_paid') and bill.currency<>v_base and bill.total_transaction-bill.paid_transaction-bill.returned_transaction>0;
  select coalesce(jsonb_agg(jsonb_build_object('id',bank.id,'name',bank.name,'institution_name',bank.institution_name,'currency',bank.currency,'ledger_account_id',bank.ledger_account_id,'opening_balance_transaction',bank.opening_balance_transaction,'opening_balance_base',bank.opening_balance_base,'mixed_currency_ledger',exists(select 1 from public.business_journal_lines line join public.business_journal_entries entry on entry.business_id=line.business_id and entry.id=line.journal_entry_id where line.business_id=p_business_id and line.account_id=bank.ledger_account_id and entry.status='posted' and entry.transaction_currency<>bank.currency and entry.source_type not in('fx_revaluation','fx_revaluation_reversal')),'latest_rate_date',rate.rate_date,'latest_rate',rate.rate_to_base) order by bank.name),'[]'::jsonb) into v_banks
  from public.business_bank_accounts bank left join lateral (select fx.rate_date,fx.rate_to_base from public.business_fx_rates fx where fx.business_id=p_business_id and fx.currency=bank.currency order by fx.rate_date desc limit 1) rate on true where bank.business_id=p_business_id and bank.is_active and bank.currency<>v_base;
  select coalesce(jsonb_agg(item order by item->>'payment_date' desc),'[]'::jsonb) into v_settlements from (
    select jsonb_build_object('type','sales_receipt','id',payment.id,'document_id',payment.invoice_id,'document_code',invoice.invoice_code,'payment_date',payment.payment_date,'currency',invoice.currency,'transaction_amount',payment.amount_transaction,'settlement_rate',payment.settlement_exchange_rate,'carrying_base',payment.carrying_amount_base,'settlement_base',payment.amount_base,'realized_gain_base',payment.realized_fx_gain_base,'realized_loss_base',payment.realized_fx_loss_base,'journal_entry_id',payment.journal_entry_id) item from public.business_sales_payments payment join public.business_sales_invoices invoice on invoice.business_id=payment.business_id and invoice.id=payment.invoice_id where payment.business_id=p_business_id and payment.status='posted' and (payment.realized_fx_gain_base>0 or payment.realized_fx_loss_base>0)
    union all
    select jsonb_build_object('type','supplier_payment','id',payment.id,'document_id',payment.bill_id,'document_code',bill.bill_code,'payment_date',payment.payment_date,'currency',bill.currency,'transaction_amount',payment.amount_transaction,'settlement_rate',payment.settlement_exchange_rate,'carrying_base',payment.carrying_amount_base,'settlement_base',payment.amount_base,'realized_gain_base',payment.realized_fx_gain_base,'realized_loss_base',payment.realized_fx_loss_base,'journal_entry_id',payment.journal_entry_id) item from public.business_supplier_payments payment join public.business_supplier_bills bill on bill.business_id=payment.business_id and bill.id=payment.bill_id where payment.business_id=p_business_id and payment.status='posted' and (payment.realized_fx_gain_base>0 or payment.realized_fx_loss_base>0)
    limit 100
  ) settlements;
  select coalesce(jsonb_agg(jsonb_build_object('id',audit.id,'rate_id',audit.rate_id,'revaluation_run_id',audit.revaluation_run_id,'action',audit.action,'metadata',audit.metadata,'created_at',audit.created_at) order by audit.created_at desc),'[]'::jsonb) into v_audit from (select * from public.business_fx_audit_log where business_id=p_business_id order by created_at desc limit 100) audit;
  select coalesce(jsonb_agg(currency order by currency),'[]'::jsonb) into v_currencies from (select currency from public.business_fx_rates where business_id=p_business_id union select currency from public.business_sales_invoices where business_id=p_business_id and currency<>v_base union select currency from public.business_supplier_bills where business_id=p_business_id and currency<>v_base union select currency from public.business_bank_accounts where business_id=p_business_id and is_active and currency<>v_base) currencies;
  v_summary:=jsonb_build_object('rate_count',(select count(*) from public.business_fx_rates where business_id=p_business_id),'foreign_receivable_count',jsonb_array_length(v_receivables),'foreign_payable_count',jsonb_array_length(v_payables),'foreign_bank_count',jsonb_array_length(v_banks),'active_revaluation_count',(select count(*) from public.business_fx_revaluation_runs where business_id=p_business_id and status='posted'),'realized_gain_base',(select coalesce(sum(realized_fx_gain_base),0) from public.business_sales_payments where business_id=p_business_id and status='posted')+(select coalesce(sum(realized_fx_gain_base),0) from public.business_supplier_payments where business_id=p_business_id and status='posted'),'realized_loss_base',(select coalesce(sum(realized_fx_loss_base),0) from public.business_sales_payments where business_id=p_business_id and status='posted')+(select coalesce(sum(realized_fx_loss_base),0) from public.business_supplier_payments where business_id=p_business_id and status='posted'));
  return jsonb_build_object('base_currency',v_base,'settings',coalesce(v_settings,'{}'::jsonb),'summary',v_summary,'currencies',v_currencies,'rates',v_rates,'runs',v_runs,'lines',v_lines,'receivables',v_receivables,'payables',v_payables,'foreign_banks',v_banks,'realized_settlements',v_settlements,'audit',v_audit,'capabilities',jsonb_build_object('can_view',private.can_view_business_fx(p_business_id),'can_manage',private.can_manage_business_fx(p_business_id),'can_revalue',private.can_revalue_business_fx(p_business_id)));
end;
$$;

create or replace function public.get_business_fx_snapshot(p_business_id uuid,p_limit integer default 200)
returns jsonb language sql stable set search_path=pg_catalog,public,private
as $$select private.get_business_fx_snapshot_internal(p_business_id,p_limit);$$;

revoke execute on function private.get_business_fx_snapshot_internal(uuid,integer) from public,anon;
grant execute on function private.get_business_fx_snapshot_internal(uuid,integer),public.get_business_fx_snapshot(uuid,integer) to authenticated;
